import { missionsDetailMock } from "@/lib/missions/mocks";

import type { AgentConfig, AgentDetail, AgentLogEntry, AgentMemoryEntry } from "./types";

type AgentBase = Omit<AgentDetail, "memory" | "logs" | "config">;

/** MOCKS STATIQUES — ids alignés sur missionAgents (src/lib/missions/mocks.ts). */
const agentsBase: AgentBase[] = [
  {
    id: "a-ceo",
    name: "CEO Agent",
    avatar: "CE",
    role: "Pilotage stratégique",
    domain: "Direction",
    version: "v2.4.1",
    status: "active",
    description:
      "Orchestre l'ensemble de la workforce IA : arbitre les priorités, consolide les signaux de chaque domaine et prépare les décisions qui remontent au comité de direction.",
    capabilities: [
      {
        id: "c-ceo-1",
        label: "Arbitrage des priorités",
        description:
          "Compare l'impact business des missions en attente et propose un ordre d'exécution argumenté.",
      },
      {
        id: "c-ceo-2",
        label: "Synthèse exécutive",
        description: "Produit un briefing quotidien consolidé à partir des 6 autres agents.",
      },
      {
        id: "c-ceo-3",
        label: "Détection de risques",
        description: "Identifie les dérives budgétaires, retards et blocages inter-domaines.",
      },
      {
        id: "c-ceo-4",
        label: "Délégation inter-agents",
        description: "Crée et assigne des missions aux agents métier avec objectifs mesurables.",
      },
    ],
    tools: [
      {
        id: "t-ceo-1",
        name: "Notion",
        category: "Documentation",
        accessLevel: "write",
        status: "connected",
      },
      {
        id: "t-ceo-2",
        name: "Slack",
        category: "Communication",
        accessLevel: "write",
        status: "connected",
      },
      {
        id: "t-ceo-3",
        name: "Google Agenda",
        category: "Productivité",
        accessLevel: "execute",
        status: "connected",
      },
    ],
    permissions: [
      { resource: "Missions", read: true, write: true, execute: true, approve: true },
      { resource: "Documents", read: true, write: true, execute: false, approve: true },
      { resource: "Finance", read: true, write: false, execute: false, approve: true },
      { resource: "CRM", read: true, write: false, execute: false, approve: false },
    ],
    kpis: [
      { label: "Décisions préparées", value: "142", trend: "up" },
      { label: "Missions orchestrées", value: "38", trend: "up" },
      { label: "Délai d'arbitrage", value: "1,4 h", trend: "down" },
    ],
    confidenceScore: 94,
    uptime: "99,8 %",
    lastActivity: "2026-08-04T07:20:00.000Z",
    collaboratesWith: ["a-sales", "a-marketing", "a-finance", "a-hr", "a-support", "a-ops"],
  },
  {
    id: "a-sales",
    name: "Sales Agent",
    avatar: "SA",
    role: "Développement commercial",
    domain: "Commercial",
    version: "v3.1.0",
    status: "active",
    description:
      "Prend en charge le cycle de vente de bout en bout : qualification des leads entrants, séquences de relance personnalisées et mise à jour continue du pipeline CRM.",
    capabilities: [
      {
        id: "c-sales-1",
        label: "Qualification des leads",
        description: "Score chaque lead selon le profil ICP et l'intention détectée.",
      },
      {
        id: "c-sales-2",
        label: "Séquences de relance",
        description: "Rédige et déclenche des relances multicanal adaptées au stade du deal.",
      },
      {
        id: "c-sales-3",
        label: "Préparation de propositions",
        description: "Génère un devis structuré à partir du besoin exprimé et du catalogue.",
      },
      {
        id: "c-sales-4",
        label: "Hygiène du pipeline",
        description: "Détecte les deals dormants et propose une action corrective.",
      },
    ],
    tools: [
      {
        id: "t-sales-1",
        name: "HubSpot",
        category: "CRM",
        accessLevel: "write",
        status: "connected",
      },
      {
        id: "t-sales-2",
        name: "Gmail",
        category: "Communication",
        accessLevel: "execute",
        status: "connected",
      },
      {
        id: "t-sales-3",
        name: "LinkedIn",
        category: "Prospection",
        accessLevel: "read",
        status: "disconnected",
      },
    ],
    permissions: [
      { resource: "CRM", read: true, write: true, execute: true, approve: false },
      { resource: "Emails", read: true, write: true, execute: true, approve: false },
      { resource: "Facturation", read: true, write: false, execute: false, approve: false },
      { resource: "Documents", read: true, write: true, execute: false, approve: false },
    ],
    kpis: [
      { label: "Leads qualifiés", value: "312", trend: "up" },
      { label: "Taux de réponse", value: "38 %", trend: "up" },
      { label: "Pipeline généré", value: "1,2 M€", trend: "up" },
    ],
    confidenceScore: 91,
    uptime: "99,4 %",
    lastActivity: "2026-08-04T08:05:00.000Z",
    collaboratesWith: ["a-ceo", "a-marketing", "a-finance"],
  },
  {
    id: "a-marketing",
    name: "Marketing Agent",
    avatar: "MA",
    role: "Acquisition",
    domain: "Marketing",
    version: "v2.9.3",
    status: "active",
    description:
      "Conçoit et pilote les campagnes d'acquisition : production de contenu, ciblage publicitaire, arbitrage budgétaire et mesure de la performance par canal.",
    capabilities: [
      {
        id: "c-mkt-1",
        label: "Production de contenu",
        description: "Rédige posts, newsletters et pages d'atterrissage alignés sur la marque.",
      },
      {
        id: "c-mkt-2",
        label: "Pilotage des campagnes",
        description: "Ajuste ciblage et budget quotidien selon le coût par lead observé.",
      },
      {
        id: "c-mkt-3",
        label: "Analyse d'audience",
        description: "Segmente la base et détecte les segments à plus fort potentiel.",
      },
    ],
    tools: [
      {
        id: "t-mkt-1",
        name: "Mailchimp",
        category: "Emailing",
        accessLevel: "execute",
        status: "connected",
      },
      {
        id: "t-mkt-2",
        name: "Meta Ads",
        category: "Publicité",
        accessLevel: "write",
        status: "error",
      },
      {
        id: "t-mkt-3",
        name: "Canva",
        category: "Création",
        accessLevel: "write",
        status: "connected",
      },
    ],
    permissions: [
      { resource: "Campagnes", read: true, write: true, execute: true, approve: false },
      { resource: "CRM", read: true, write: false, execute: false, approve: false },
      { resource: "Documents", read: true, write: true, execute: false, approve: false },
      { resource: "Budget marketing", read: true, write: true, execute: false, approve: false },
    ],
    kpis: [
      { label: "Coût par lead", value: "18 €", trend: "down" },
      { label: "Contenus publiés", value: "86", trend: "up" },
      { label: "Trafic généré", value: "42 k", trend: "up" },
    ],
    confidenceScore: 88,
    uptime: "98,9 %",
    lastActivity: "2026-08-04T06:45:00.000Z",
    collaboratesWith: ["a-ceo", "a-sales"],
  },
  {
    id: "a-finance",
    name: "Finance Agent",
    avatar: "FI",
    role: "Analyse financière",
    domain: "Finance",
    version: "v3.0.2",
    status: "active",
    description:
      "Sécurise la trésorerie et la rentabilité : rapprochement des flux, suivi des impayés, prévisions de cash et contrôle des coûts d'exécution IA.",
    capabilities: [
      {
        id: "c-fin-1",
        label: "Rapprochement bancaire",
        description: "Réconcilie les encaissements Stripe avec les écritures bancaires.",
      },
      {
        id: "c-fin-2",
        label: "Prévision de trésorerie",
        description: "Projette le cash à 90 jours selon le pipeline et les échéances connues.",
      },
      {
        id: "c-fin-3",
        label: "Recouvrement",
        description: "Séquence les relances d'impayés en respectant les seuils autorisés.",
      },
      {
        id: "c-fin-4",
        label: "Contrôle des coûts IA",
        description: "Suit la consommation par mission et alerte au-delà du budget.",
      },
    ],
    tools: [
      {
        id: "t-fin-1",
        name: "Stripe",
        category: "Paiement",
        accessLevel: "read",
        status: "connected",
      },
      {
        id: "t-fin-2",
        name: "Qonto",
        category: "Banque",
        accessLevel: "read",
        status: "connected",
      },
      {
        id: "t-fin-3",
        name: "Google Sheets",
        category: "Finance",
        accessLevel: "write",
        status: "connected",
      },
    ],
    permissions: [
      { resource: "Facturation", read: true, write: true, execute: true, approve: true },
      { resource: "Comptabilité", read: true, write: true, execute: false, approve: false },
      { resource: "CRM", read: true, write: false, execute: false, approve: false },
      { resource: "Documents", read: true, write: true, execute: false, approve: false },
    ],
    kpis: [
      { label: "Marge suivie", value: "68 %", trend: "up" },
      { label: "Impayés relancés", value: "27", trend: "down" },
      { label: "Écart prévisionnel", value: "2,1 %", trend: "flat" },
    ],
    confidenceScore: 96,
    uptime: "99,9 %",
    lastActivity: "2026-08-04T07:55:00.000Z",
    collaboratesWith: ["a-ceo", "a-sales", "a-ops"],
  },
  {
    id: "a-hr",
    name: "HR Agent",
    avatar: "HR",
    role: "Ressources humaines",
    domain: "RH",
    version: "v1.8.0",
    status: "maintenance",
    description:
      "Fluidifie le cycle de vie collaborateur : tri des candidatures, coordination des entretiens, onboarding documentaire et suivi des demandes internes.",
    capabilities: [
      {
        id: "c-hr-1",
        label: "Tri des candidatures",
        description: "Classe les CV reçus selon la grille de compétences du poste.",
      },
      {
        id: "c-hr-2",
        label: "Coordination d'entretiens",
        description: "Propose des créneaux et envoie les convocations aux parties prenantes.",
      },
      {
        id: "c-hr-3",
        label: "Onboarding",
        description: "Génère et fait signer le pack d'arrivée du nouveau collaborateur.",
      },
    ],
    tools: [
      { id: "t-hr-1", name: "Personio", category: "RH", accessLevel: "write", status: "connected" },
      {
        id: "t-hr-2",
        name: "Gmail",
        category: "Communication",
        accessLevel: "execute",
        status: "connected",
      },
      {
        id: "t-hr-3",
        name: "DocuSign",
        category: "Signature",
        accessLevel: "approve",
        status: "disconnected",
      },
    ],
    permissions: [
      { resource: "Dossiers RH", read: true, write: true, execute: false, approve: false },
      { resource: "Emails", read: true, write: true, execute: true, approve: false },
      { resource: "Documents", read: true, write: true, execute: false, approve: true },
      { resource: "Facturation", read: false, write: false, execute: false, approve: false },
    ],
    kpis: [
      { label: "Candidatures traitées", value: "418", trend: "up" },
      { label: "Délai de recrutement", value: "24 j", trend: "down" },
      { label: "Onboardings", value: "12", trend: "flat" },
    ],
    confidenceScore: 82,
    uptime: "97,2 %",
    lastActivity: "2026-08-03T16:10:00.000Z",
    collaboratesWith: ["a-ceo", "a-ops"],
  },
  {
    id: "a-support",
    name: "Support Agent",
    avatar: "SU",
    role: "Relation client",
    domain: "Support",
    version: "v4.0.1",
    status: "active",
    description:
      "Absorbe le premier niveau de support : réponse aux demandes récurrentes, escalade qualifiée des cas complexes et surveillance de la satisfaction client.",
    capabilities: [
      {
        id: "c-sup-1",
        label: "Réponse niveau 1",
        description: "Traite les tickets récurrents à partir de l'Enterprise Brain.",
      },
      {
        id: "c-sup-2",
        label: "Escalade qualifiée",
        description: "Résume le contexte et route le ticket vers la bonne équipe.",
      },
      {
        id: "c-sup-3",
        label: "Veille satisfaction",
        description: "Détecte les signaux d'insatisfaction et alerte le Sales Agent.",
      },
      {
        id: "c-sup-4",
        label: "Enrichissement FAQ",
        description: "Propose de nouveaux articles à partir des tickets répétitifs.",
      },
    ],
    tools: [
      {
        id: "t-sup-1",
        name: "Zendesk",
        category: "Support",
        accessLevel: "write",
        status: "connected",
      },
      {
        id: "t-sup-2",
        name: "Intercom",
        category: "Support",
        accessLevel: "execute",
        status: "connected",
      },
      {
        id: "t-sup-3",
        name: "Slack",
        category: "Communication",
        accessLevel: "write",
        status: "connected",
      },
    ],
    permissions: [
      { resource: "Tickets", read: true, write: true, execute: true, approve: false },
      { resource: "CRM", read: true, write: true, execute: false, approve: false },
      { resource: "Documents", read: true, write: false, execute: false, approve: false },
      { resource: "Facturation", read: true, write: false, execute: false, approve: false },
    ],
    kpis: [
      { label: "Tickets résolus", value: "1 284", trend: "up" },
      { label: "Temps de réponse", value: "3 min", trend: "down" },
      { label: "CSAT", value: "4,6/5", trend: "up" },
    ],
    confidenceScore: 93,
    uptime: "99,6 %",
    lastActivity: "2026-08-04T08:25:00.000Z",
    collaboratesWith: ["a-ceo", "a-sales", "a-ops"],
  },
  {
    id: "a-ops",
    name: "Operations Agent",
    avatar: "OP",
    role: "Opérations",
    domain: "Opérations",
    version: "v2.6.4",
    status: "paused",
    description:
      "Garantit l'exécution opérationnelle : suivi des livrables, automatisation des tâches répétitives et surveillance de la santé des intégrations.",
    capabilities: [
      {
        id: "c-ops-1",
        label: "Suivi des livrables",
        description: "Contrôle l'avancement des tâches Jira et signale les retards.",
      },
      {
        id: "c-ops-2",
        label: "Automatisation",
        description: "Déclenche les scénarios Zapier liés aux processus internes.",
      },
      {
        id: "c-ops-3",
        label: "Supervision des intégrations",
        description: "Vérifie la santé des connecteurs et remonte les incidents.",
      },
    ],
    tools: [
      {
        id: "t-ops-1",
        name: "Jira",
        category: "Projet",
        accessLevel: "write",
        status: "connected",
      },
      {
        id: "t-ops-2",
        name: "Google Drive",
        category: "Documentation",
        accessLevel: "write",
        status: "connected",
      },
      {
        id: "t-ops-3",
        name: "Zapier",
        category: "Automatisation",
        accessLevel: "execute",
        status: "error",
      },
    ],
    permissions: [
      { resource: "Projets", read: true, write: true, execute: true, approve: false },
      { resource: "Documents", read: true, write: true, execute: false, approve: false },
      { resource: "Intégrations", read: true, write: false, execute: true, approve: false },
      { resource: "Facturation", read: false, write: false, execute: false, approve: false },
    ],
    kpis: [
      { label: "Tâches automatisées", value: "2 140", trend: "up" },
      { label: "Incidents ouverts", value: "3", trend: "down" },
      { label: "Temps économisé", value: "312 h", trend: "up" },
    ],
    confidenceScore: 87,
    uptime: "98,1 %",
    lastActivity: "2026-08-03T21:40:00.000Z",
    collaboratesWith: ["a-ceo", "a-finance", "a-hr", "a-support"],
  },
];

/** Mémoire mockée par agent (4 niveaux : working / long_term / shared / enterprise_brain). */
const memoryByAgent: Record<string, AgentMemoryEntry[]> = {
  "a-ceo": [
    {
      id: "mem-ceo-1",
      level: "working",
      title: "Arbitrage du trimestre en cours",
      content:
        "Priorité donnée à l'expansion commerciale avant l'optimisation des coûts, tant que la marge reste au-dessus de 65 %.",
      source: "Mission #m-1",
      confidenceScore: 92,
      createdAt: "2026-08-01T09:00:00.000Z",
      lastAccessed: "2026-08-04T07:20:00.000Z",
    },
    {
      id: "mem-ceo-2",
      level: "long_term",
      title: "Cadence des comités de direction",
      content:
        "Le comité attend une synthèse de 5 points maximum, chiffrée, envoyée la veille à 18 h.",
      source: "Préférence apprise",
      confidenceScore: 88,
      createdAt: "2026-05-12T16:30:00.000Z",
      lastAccessed: "2026-08-03T18:05:00.000Z",
    },
    {
      id: "mem-ceo-3",
      level: "shared",
      title: "Vocabulaire commun des priorités",
      content:
        "P0 = bloquant client, P1 = impact chiffre d'affaires, P2 = amélioration interne. Partagé avec tous les agents métier.",
      source: "Workforce IA",
      confidenceScore: 95,
      createdAt: "2026-04-02T10:15:00.000Z",
      lastAccessed: "2026-08-04T06:40:00.000Z",
    },
    {
      id: "mem-ceo-4",
      sourceId: "kb-objectifs-2026",
      level: "enterprise_brain",
      title: "Objectifs annuels 2026",
      content: "Croissance ARR +40 %, marge brute ≥ 68 %, NPS ≥ 55.",
      source: "Enterprise Brain",
      confidenceScore: null,
      createdAt: "2026-01-08T08:00:00.000Z",
      lastAccessed: "2026-08-04T07:10:00.000Z",
    },
  ],
  "a-sales": [
    {
      id: "mem-sales-1",
      level: "working",
      title: "Deals en négociation",
      content: "3 deals > 100 k€ en phase finale, relance prévue sous 48 h sur chacun.",
      source: "Mission #m-10",
      confidenceScore: 84,
      createdAt: "2026-08-02T11:20:00.000Z",
      lastAccessed: "2026-08-04T08:05:00.000Z",
    },
    {
      id: "mem-sales-2",
      level: "long_term",
      title: "Profil ICP validé",
      content:
        "Meilleure conversion sur les PME industrielles 50-250 salariés en France et Benelux.",
      source: "Analyse historique CRM",
      confidenceScore: 90,
      createdAt: "2026-03-18T09:45:00.000Z",
      lastAccessed: "2026-08-03T14:00:00.000Z",
    },
    {
      id: "mem-sales-3",
      sourceId: "kb-grille-tarifaire",
      level: "enterprise_brain",
      title: "Grille tarifaire officielle",
      content: "Remise maximale autorisée : 12 % sans validation, 20 % avec validation Finance.",
      source: "Enterprise Brain",
      confidenceScore: null,
      createdAt: "2026-02-01T08:00:00.000Z",
      lastAccessed: "2026-08-04T07:50:00.000Z",
    },
  ],
  "a-marketing": [
    {
      id: "mem-mkt-1",
      level: "working",
      title: "Campagne d'été en cours",
      content: "Budget quotidien plafonné à 400 € tant que le coût par lead dépasse 20 €.",
      source: "Mission #m-6",
      confidenceScore: 79,
      createdAt: "2026-07-28T10:00:00.000Z",
      lastAccessed: "2026-08-04T06:45:00.000Z",
    },
    {
      id: "mem-mkt-2",
      level: "shared",
      title: "Ton de marque",
      content: "Direct, factuel, sans superlatif. Partagé avec Sales et Support.",
      source: "Charte éditoriale",
      confidenceScore: 93,
      createdAt: "2026-04-22T13:30:00.000Z",
      lastAccessed: "2026-08-02T09:10:00.000Z",
    },
    {
      id: "mem-mkt-3",
      level: "long_term",
      title: "Canaux les plus rentables",
      content: "LinkedIn Ads > Newsletter > Meta Ads sur les 12 derniers mois.",
      source: "Analyse multicanal",
      confidenceScore: 86,
      createdAt: "2026-01-30T15:00:00.000Z",
      lastAccessed: "2026-08-01T17:20:00.000Z",
    },
  ],
  "a-finance": [
    {
      id: "mem-fin-1",
      level: "working",
      title: "Clôture mensuelle en cours",
      content: "12 écritures en attente de rapprochement sur le compte principal.",
      source: "Mission #m-5",
      confidenceScore: 91,
      createdAt: "2026-08-01T07:30:00.000Z",
      lastAccessed: "2026-08-04T07:55:00.000Z",
    },
    {
      id: "mem-fin-2",
      level: "long_term",
      title: "Saisonnalité du cash",
      content: "Creux de trésorerie systématique en août, pic d'encaissement en décembre.",
      source: "Historique 3 ans",
      confidenceScore: 94,
      createdAt: "2025-12-15T09:00:00.000Z",
      lastAccessed: "2026-08-03T11:40:00.000Z",
    },
    {
      id: "mem-fin-3",
      level: "shared",
      title: "Seuils de relance impayés",
      content: "Relance à J+7, J+15 puis escalade Sales à J+30.",
      source: "Workforce IA",
      confidenceScore: 89,
      createdAt: "2026-03-05T10:00:00.000Z",
      lastAccessed: "2026-08-04T06:20:00.000Z",
    },
    {
      id: "mem-fin-4",
      sourceId: "kb-politique-depenses",
      level: "enterprise_brain",
      title: "Politique de dépenses",
      content: "Toute dépense > 5 000 € requiert une validation humaine explicite.",
      source: "Enterprise Brain",
      confidenceScore: null,
      createdAt: "2026-01-08T08:00:00.000Z",
      lastAccessed: "2026-08-04T07:00:00.000Z",
    },
  ],
  // Agent récemment redéployé : aucune mémoire long terme ni partagée pour l'instant.
  "a-hr": [
    {
      id: "mem-hr-1",
      level: "working",
      title: "Recrutements ouverts",
      content: "2 postes en cours : Data Engineer et Customer Success Manager.",
      source: "Mission #m-5",
      confidenceScore: 76,
      createdAt: "2026-08-03T09:00:00.000Z",
      lastAccessed: "2026-08-03T16:10:00.000Z",
    },
    {
      id: "mem-hr-2",
      sourceId: "kb-convention-collective",
      level: "enterprise_brain",
      title: "Convention collective applicable",
      content: "Syntec — période d'essai 4 mois renouvelable une fois pour les cadres.",
      source: "Enterprise Brain",
      confidenceScore: null,
      createdAt: "2026-02-10T08:00:00.000Z",
      lastAccessed: "2026-08-03T15:45:00.000Z",
    },
  ],
  "a-support": [
    {
      id: "mem-sup-1",
      level: "working",
      title: "Incident en cours",
      content: "Latence signalée sur l'export PDF depuis ce matin, 14 tickets liés.",
      source: "Mission #m-3",
      confidenceScore: 81,
      createdAt: "2026-08-04T06:10:00.000Z",
      lastAccessed: "2026-08-04T08:25:00.000Z",
    },
    {
      id: "mem-sup-2",
      level: "long_term",
      title: "Top 5 des demandes récurrentes",
      content:
        "Réinitialisation de mot de passe, export de données, facturation, SSO, limites d'API.",
      source: "Analyse des tickets",
      confidenceScore: 92,
      createdAt: "2026-05-02T12:00:00.000Z",
      lastAccessed: "2026-08-04T07:30:00.000Z",
    },
    {
      id: "mem-sup-3",
      level: "shared",
      title: "Signaux d'insatisfaction",
      content: "CSAT < 3 sur deux tickets consécutifs → alerte immédiate au Sales Agent.",
      source: "Workforce IA",
      confidenceScore: 87,
      createdAt: "2026-06-11T10:20:00.000Z",
      lastAccessed: "2026-08-04T08:00:00.000Z",
    },
  ],
  "a-ops": [
    {
      id: "mem-ops-1",
      level: "working",
      title: "Connecteur Zapier en erreur",
      content: "Le scénario de synchronisation Drive échoue depuis hier soir, reprise suspendue.",
      source: "Mission #m-3",
      confidenceScore: 68,
      createdAt: "2026-08-03T20:15:00.000Z",
      lastAccessed: "2026-08-03T21:40:00.000Z",
    },
    {
      id: "mem-ops-2",
      level: "long_term",
      title: "Fenêtre de maintenance",
      content: "Les déploiements sont interdits le vendredi après 15 h.",
      source: "Préférence apprise",
      confidenceScore: 90,
      createdAt: "2026-02-28T09:00:00.000Z",
      lastAccessed: "2026-08-01T14:10:00.000Z",
    },
    {
      id: "mem-ops-3",
      level: "shared",
      title: "Format de compte rendu d'incident",
      content: "Impact, cause, correctif, prévention — dans cet ordre, en moins de 10 lignes.",
      source: "Workforce IA",
      confidenceScore: 85,
      createdAt: "2026-04-15T11:00:00.000Z",
      lastAccessed: "2026-08-02T10:30:00.000Z",
    },
  ],
};

/** Logs mockés par agent, cohérents avec les missions associées. */
const logsByAgent: Record<string, AgentLogEntry[]> = {
  "a-ceo": [
    {
      id: "log-ceo-1",
      timestamp: "2026-08-04T07:20:00.000Z",
      type: "decision",
      action: "Arbitrage : priorité donnée à l'expansion commerciale",
      tool: null,
      missionId: "m-1",
      result: "success",
      durationMs: 4200,
      costEstimate: "0,18 €",
    },
    {
      id: "log-ceo-2",
      timestamp: "2026-08-04T06:50:00.000Z",
      type: "handoff",
      action: "Délégation de l'analyse de marge au Finance Agent",
      tool: null,
      missionId: "m-9",
      result: "success",
      durationMs: 1100,
      costEstimate: "0,04 €",
    },
    {
      id: "log-ceo-3",
      timestamp: "2026-08-04T06:30:00.000Z",
      type: "tool_call",
      action: "Publication du briefing quotidien",
      tool: "Notion",
      missionId: null,
      result: "success",
      durationMs: 2600,
      costEstimate: "0,02 €",
    },
    {
      id: "log-ceo-4",
      timestamp: "2026-08-03T18:05:00.000Z",
      type: "validation",
      action: "Validation humaine demandée sur le budget marketing",
      tool: "Slack",
      missionId: "m-1",
      result: "pending",
      durationMs: null,
      costEstimate: null,
    },
    {
      id: "log-ceo-5",
      timestamp: "2026-08-03T15:12:00.000Z",
      type: "tool_call",
      action: "Création du créneau de comité de direction",
      tool: "Google Agenda",
      missionId: null,
      result: "success",
      durationMs: 900,
      costEstimate: "0,01 €",
    },
  ],
  "a-sales": [
    {
      id: "log-sales-1",
      timestamp: "2026-08-04T08:05:00.000Z",
      type: "tool_call",
      action: "Mise à jour de 14 fiches deal",
      tool: "HubSpot",
      missionId: "m-10",
      result: "success",
      durationMs: 5400,
      costEstimate: "0,12 €",
    },
    {
      id: "log-sales-2",
      timestamp: "2026-08-04T07:40:00.000Z",
      type: "tool_call",
      action: "Envoi de 23 relances personnalisées",
      tool: "Gmail",
      missionId: "m-10",
      result: "success",
      durationMs: 8200,
      costEstimate: "0,31 €",
    },
    {
      id: "log-sales-3",
      timestamp: "2026-08-04T07:05:00.000Z",
      type: "error",
      action: "Échec de l'enrichissement de profil",
      tool: "LinkedIn",
      missionId: null,
      result: "failure",
      durationMs: 1500,
      costEstimate: null,
    },
    {
      id: "log-sales-4",
      timestamp: "2026-08-03T17:20:00.000Z",
      type: "decision",
      action: "Requalification de 8 leads en priorité basse",
      tool: null,
      missionId: "m-1",
      result: "success",
      durationMs: 3100,
      costEstimate: "0,09 €",
    },
    {
      id: "log-sales-5",
      timestamp: "2026-08-03T11:00:00.000Z",
      type: "validation",
      action: "Remise de 18 % soumise au Finance Agent",
      tool: null,
      missionId: "m-9",
      result: "success",
      durationMs: 2400,
      costEstimate: "0,05 €",
    },
  ],
  "a-marketing": [
    {
      id: "log-mkt-1",
      timestamp: "2026-08-04T06:45:00.000Z",
      type: "tool_call",
      action: "Envoi de la newsletter hebdomadaire",
      tool: "Mailchimp",
      missionId: "m-6",
      result: "success",
      durationMs: 6100,
      costEstimate: "0,22 €",
    },
    {
      id: "log-mkt-2",
      timestamp: "2026-08-04T05:30:00.000Z",
      type: "error",
      action: "Synchronisation des audiences interrompue",
      tool: "Meta Ads",
      missionId: "m-7",
      result: "failure",
      durationMs: 2200,
      costEstimate: null,
    },
    {
      id: "log-mkt-3",
      timestamp: "2026-08-03T16:10:00.000Z",
      type: "decision",
      action: "Réallocation de 30 % du budget vers LinkedIn Ads",
      tool: null,
      missionId: "m-7",
      result: "success",
      durationMs: 3700,
      costEstimate: "0,10 €",
    },
    {
      id: "log-mkt-4",
      timestamp: "2026-08-03T10:25:00.000Z",
      type: "tool_call",
      action: "Génération de 6 visuels de campagne",
      tool: "Canva",
      missionId: "m-6",
      result: "success",
      durationMs: 9400,
      costEstimate: "0,44 €",
    },
  ],
  "a-finance": [
    {
      id: "log-fin-1",
      timestamp: "2026-08-04T07:55:00.000Z",
      type: "tool_call",
      action: "Rapprochement de 128 transactions",
      tool: "Qonto",
      missionId: "m-5",
      result: "success",
      durationMs: 12400,
      costEstimate: "0,38 €",
    },
    {
      id: "log-fin-2",
      timestamp: "2026-08-04T07:10:00.000Z",
      type: "validation",
      action: "Validation humaine requise sur une dépense de 8 400 €",
      tool: null,
      missionId: "m-8",
      result: "pending",
      durationMs: null,
      costEstimate: null,
    },
    {
      id: "log-fin-3",
      timestamp: "2026-08-04T06:20:00.000Z",
      type: "tool_call",
      action: "Extraction des encaissements du mois",
      tool: "Stripe",
      missionId: "m-5",
      result: "success",
      durationMs: 3300,
      costEstimate: "0,07 €",
    },
    {
      id: "log-fin-4",
      timestamp: "2026-08-03T18:40:00.000Z",
      type: "handoff",
      action: "Transmission du prévisionnel au CEO Agent",
      tool: null,
      missionId: "m-9",
      result: "success",
      durationMs: 1200,
      costEstimate: "0,03 €",
    },
    {
      id: "log-fin-5",
      timestamp: "2026-08-03T14:05:00.000Z",
      type: "decision",
      action: "Blocage d'une remise dépassant le seuil autorisé",
      tool: null,
      missionId: "m-9",
      result: "success",
      durationMs: 2100,
      costEstimate: "0,05 €",
    },
    {
      id: "log-fin-6",
      timestamp: "2026-08-02T09:30:00.000Z",
      type: "tool_call",
      action: "Mise à jour du tableau de trésorerie",
      tool: "Google Sheets",
      missionId: null,
      result: "success",
      durationMs: 4600,
      costEstimate: "0,06 €",
    },
  ],
  "a-hr": [
    {
      id: "log-hr-1",
      timestamp: "2026-08-03T16:10:00.000Z",
      type: "tool_call",
      action: "Tri de 42 candidatures reçues",
      tool: "Personio",
      missionId: "m-5",
      result: "success",
      durationMs: 7300,
      costEstimate: "0,19 €",
    },
    {
      id: "log-hr-2",
      timestamp: "2026-08-03T14:50:00.000Z",
      type: "tool_call",
      action: "Envoi de 6 convocations d'entretien",
      tool: "Gmail",
      missionId: "m-5",
      result: "success",
      durationMs: 2800,
      costEstimate: "0,05 €",
    },
    {
      id: "log-hr-3",
      timestamp: "2026-08-03T11:15:00.000Z",
      type: "error",
      action: "Envoi du pack d'onboarding impossible",
      tool: "DocuSign",
      missionId: "m-6",
      result: "failure",
      durationMs: 1700,
      costEstimate: null,
    },
    {
      id: "log-hr-4",
      timestamp: "2026-08-02T15:00:00.000Z",
      type: "handoff",
      action: "Transfert du dossier d'embauche au Finance Agent",
      tool: null,
      missionId: "m-6",
      result: "success",
      durationMs: 1000,
      costEstimate: "0,02 €",
    },
  ],
  "a-support": [
    {
      id: "log-sup-1",
      timestamp: "2026-08-04T08:25:00.000Z",
      type: "tool_call",
      action: "Résolution automatique de 18 tickets niveau 1",
      tool: "Zendesk",
      missionId: "m-3",
      result: "success",
      durationMs: 9800,
      costEstimate: "0,27 €",
    },
    {
      id: "log-sup-2",
      timestamp: "2026-08-04T07:45:00.000Z",
      type: "handoff",
      action: "Escalade d'un incident export vers l'Operations Agent",
      tool: "Slack",
      missionId: "m-3",
      result: "success",
      durationMs: 1300,
      costEstimate: "0,03 €",
    },
    {
      id: "log-sup-3",
      timestamp: "2026-08-04T07:00:00.000Z",
      type: "decision",
      action: "Priorisation des tickets liés à la latence d'export",
      tool: null,
      missionId: "m-3",
      result: "success",
      durationMs: 2000,
      costEstimate: "0,04 €",
    },
    {
      id: "log-sup-4",
      timestamp: "2026-08-03T19:20:00.000Z",
      type: "tool_call",
      action: "Réponse à 9 conversations entrantes",
      tool: "Intercom",
      missionId: "m-2",
      result: "success",
      durationMs: 5200,
      costEstimate: "0,14 €",
    },
    {
      id: "log-sup-5",
      timestamp: "2026-08-03T12:10:00.000Z",
      type: "validation",
      action: "Proposition de 3 nouveaux articles FAQ soumise",
      tool: null,
      missionId: null,
      result: "pending",
      durationMs: null,
      costEstimate: null,
    },
  ],
  "a-ops": [
    {
      id: "log-ops-1",
      timestamp: "2026-08-03T21:40:00.000Z",
      type: "error",
      action: "Scénario de synchronisation Drive en échec",
      tool: "Zapier",
      missionId: "m-3",
      result: "failure",
      durationMs: 3100,
      costEstimate: null,
    },
    {
      id: "log-ops-2",
      timestamp: "2026-08-03T18:00:00.000Z",
      type: "tool_call",
      action: "Mise à jour de 27 tickets de suivi",
      tool: "Jira",
      missionId: "m-3",
      result: "success",
      durationMs: 6400,
      costEstimate: "0,16 €",
    },
    {
      id: "log-ops-3",
      timestamp: "2026-08-03T15:30:00.000Z",
      type: "decision",
      action: "Suspension des automatisations non critiques",
      tool: null,
      missionId: "m-4",
      result: "success",
      durationMs: 1800,
      costEstimate: "0,04 €",
    },
    {
      id: "log-ops-4",
      timestamp: "2026-08-03T10:00:00.000Z",
      type: "tool_call",
      action: "Archivage des livrables du mois",
      tool: "Google Drive",
      missionId: "m-8",
      result: "success",
      durationMs: 4300,
      costEstimate: "0,08 €",
    },
    {
      id: "log-ops-5",
      timestamp: "2026-08-02T16:45:00.000Z",
      type: "handoff",
      action: "Remontée d'incident au CEO Agent",
      tool: null,
      missionId: "m-4",
      result: "success",
      durationMs: 1100,
      costEstimate: "0,02 €",
    },
  ],
};

/** Configuration mockée par agent (lecture seule). */
const configByAgent: Record<string, AgentConfig> = {
  "a-ceo": {
    language: "Français",
    timezone: "Europe/Paris",
    autonomyLevel: "semi_autonomous",
    executionFrequency: "Temps réel",
    notificationsEnabled: true,
    validationThreshold: "critical_only",
    enabledTools: ["t-ceo-1", "t-ceo-2", "t-ceo-3"],
    usageLimits: [
      { label: "Appels IA / jour", value: "2 000" },
      { label: "Budget mensuel", value: "600 €" },
      { label: "Missions simultanées", value: "10" },
    ],
  },
  "a-sales": {
    language: "Français",
    timezone: "Europe/Paris",
    autonomyLevel: "semi_autonomous",
    executionFrequency: "Toutes les 15 minutes",
    notificationsEnabled: true,
    validationThreshold: "critical_only",
    enabledTools: ["t-sales-1", "t-sales-2"],
    usageLimits: [
      { label: "Emails / jour", value: "250" },
      { label: "Budget mensuel", value: "400 €" },
      { label: "Deals suivis", value: "180" },
    ],
  },
  "a-marketing": {
    language: "Français",
    timezone: "Europe/Paris",
    autonomyLevel: "semi_autonomous",
    executionFrequency: "Toutes les heures",
    notificationsEnabled: true,
    validationThreshold: "critical_only",
    enabledTools: ["t-mkt-1", "t-mkt-3"],
    usageLimits: [
      { label: "Contenus / semaine", value: "20" },
      { label: "Budget publicitaire / jour", value: "400 €" },
      { label: "Budget IA mensuel", value: "350 €" },
    ],
  },
  "a-finance": {
    language: "Français",
    timezone: "Europe/Paris",
    autonomyLevel: "supervised",
    executionFrequency: "Toutes les heures",
    notificationsEnabled: true,
    validationThreshold: "all_actions",
    enabledTools: ["t-fin-1", "t-fin-2", "t-fin-3"],
    usageLimits: [
      { label: "Appels IA / jour", value: "1 200" },
      { label: "Montant sans validation", value: "0 €" },
      { label: "Budget mensuel", value: "500 €" },
    ],
  },
  "a-hr": {
    language: "Français",
    timezone: "Europe/Paris",
    autonomyLevel: "supervised",
    executionFrequency: "Quotidienne",
    notificationsEnabled: false,
    validationThreshold: "all_actions",
    enabledTools: ["t-hr-1", "t-hr-2"],
    usageLimits: [
      { label: "Candidatures / jour", value: "150" },
      { label: "Budget mensuel", value: "200 €" },
    ],
  },
  "a-support": {
    language: "Français",
    timezone: "Europe/Paris",
    autonomyLevel: "autonomous",
    executionFrequency: "Temps réel",
    notificationsEnabled: true,
    validationThreshold: "none",
    enabledTools: ["t-sup-1", "t-sup-2", "t-sup-3"],
    usageLimits: [
      { label: "Tickets / jour", value: "600" },
      { label: "Budget mensuel", value: "450 €" },
      { label: "Conversations simultanées", value: "40" },
    ],
  },
  "a-ops": {
    language: "Français",
    timezone: "Europe/Paris",
    autonomyLevel: "semi_autonomous",
    executionFrequency: "Toutes les 30 minutes",
    notificationsEnabled: true,
    validationThreshold: "critical_only",
    enabledTools: ["t-ops-1", "t-ops-2"],
    usageLimits: [
      { label: "Automatisations / jour", value: "800" },
      { label: "Budget mensuel", value: "300 €" },
    ],
  },
};

export const agentsDetailMock: AgentDetail[] = agentsBase.map((agent) => ({
  ...agent,
  memory: memoryByAgent[agent.id] ?? [],
  logs: logsByAgent[agent.id] ?? [],
  config: configByAgent[agent.id]!,
}));

/** Missions (mocks) dans lesquelles l'agent intervient. */
export function missionsOfAgent(agentId: string) {
  return missionsDetailMock.filter((m) => m.agents.some((a) => a.id === agentId));
}
