import { agentsDetailMock } from "@/lib/agents/mocks";
import type { AgentDetail } from "@/lib/agents/types";
import { missionsDetailMock } from "@/lib/missions/mocks";
import type { MissionDetail } from "@/lib/missions/types";

import type { Workflow } from "./types";

/** Mocks statiques — aucune persistance, aucune exécution réelle. */
export const workflowsMock: Workflow[] = [
  {
    id: "wf-1",
    name: "Relance automatique des prospects inactifs",
    description:
      "Détecte les prospects sans interaction depuis 30 jours et déclenche une séquence de relance personnalisée par le Sales Agent.",
    status: "active",
    triggerKind: "scheduled",
    scheduleExpression: "Tous les jours à 8h00 (Europe/Paris)",
    agentId: "a-sales",
    relatedMissionIds: ["m-1"],
    variables: [
      { name: "inactivity_days", type: "number", defaultValue: "30" },
      { name: "max_relances", type: "number", defaultValue: "3" },
      { name: "canal_prioritaire", type: "string", defaultValue: "email" },
    ],
    nodes: [
      {
        id: "wf-1-n1",
        type: "trigger",
        label: "Planification quotidienne",
        description: "Exécution automatique chaque matin à 8h00.",
      },
      {
        id: "wf-1-n2",
        type: "action",
        label: "Extraire les prospects inactifs",
        description: "Requête CRM sur les contacts sans activité depuis inactivity_days.",
        tool: "CRM Query",
      },
      {
        id: "wf-1-n3",
        type: "condition",
        label: "Le prospect a-t-il un score > 60 ?",
        description: "Oriente vers une relance personnalisée ou une séquence générique.",
        branches: [
          { label: "Oui", nodeIds: ["wf-1-b1", "wf-1-b2"] },
          { label: "Non", nodeIds: ["wf-1-b3"] },
        ],
      },
      {
        id: "wf-1-b1",
        type: "action",
        label: "Rédiger un e-mail personnalisé",
        description: "Génération du message à partir de l'historique du contact.",
        tool: "LLM Composer",
      },
      {
        id: "wf-1-b2",
        type: "action",
        label: "Notifier le commercial référent",
        description: "Message interne pour un suivi humain sous 48h.",
        tool: "Slack",
      },
      {
        id: "wf-1-b3",
        type: "action",
        label: "Ajouter à la séquence générique",
        description: "Insertion dans la campagne de nurturing standard.",
        tool: "Email Sequencer",
      },
      {
        id: "wf-1-n4",
        type: "loop",
        label: "Pour chaque prospect sélectionné",
        description: "Répète l'envoi jusqu'à max_relances ou jusqu'à réponse.",
      },
      {
        id: "wf-1-n5",
        type: "action",
        label: "Mettre à jour le CRM",
        description: "Journalise l'activité et met à jour lastContactAt.",
        tool: "CRM Update",
      },
    ],
    successRate: 96,
    avgDurationMs: 184000,
    lastRunAt: "2026-08-06T06:00:00+02:00",
    runs: [
      {
        id: "wf-1-r5",
        startedAt: "2026-08-06T06:00:00+02:00",
        finishedAt: "2026-08-06T06:03:12+02:00",
        status: "success",
        triggeredBy: "Planifié",
        durationMs: 192000,
        errorMessage: null,
        nodesExecuted: 8,
        nodesTotal: 8,
      },
      {
        id: "wf-1-r4",
        startedAt: "2026-08-05T06:00:00+02:00",
        finishedAt: "2026-08-05T06:02:51+02:00",
        status: "success",
        triggeredBy: "Planifié",
        durationMs: 171000,
        errorMessage: null,
        nodesExecuted: 8,
        nodesTotal: 8,
      },
      {
        id: "wf-1-r3",
        startedAt: "2026-08-04T06:00:00+02:00",
        finishedAt: "2026-08-04T06:01:04+02:00",
        status: "failure",
        triggeredBy: "Planifié",
        durationMs: 64000,
        errorMessage:
          "Quota de l'API d'envoi atteint (429 Too Many Requests) — 42 relances non envoyées.",
        nodesExecuted: 5,
        nodesTotal: 8,
      },
      {
        id: "wf-1-r2",
        startedAt: "2026-08-03T06:00:00+02:00",
        finishedAt: "2026-08-03T06:03:40+02:00",
        status: "success",
        triggeredBy: "Sales Agent",
        durationMs: 220000,
        errorMessage: null,
        nodesExecuted: 8,
        nodesTotal: 8,
      },
      {
        id: "wf-1-r1",
        startedAt: "2026-08-02T06:00:00+02:00",
        finishedAt: "2026-08-02T06:02:35+02:00",
        status: "success",
        triggeredBy: "Planifié",
        durationMs: 155000,
        errorMessage: null,
        nodesExecuted: 8,
        nodesTotal: 8,
      },
    ],
    createdAt: "2026-03-11T10:00:00+01:00",
    updatedAt: "2026-07-29T16:40:00+02:00",
  },
  {
    id: "wf-2",
    name: "Clôture mensuelle",
    description:
      "Consolide les écritures comptables, contrôle les écarts de marge et produit la synthèse exécutive du mois.",
    status: "active",
    triggerKind: "scheduled",
    scheduleExpression: "Le 1er de chaque mois à 05h30",
    agentId: "a-finance",
    relatedMissionIds: ["m-2", "m-5"],
    variables: [
      { name: "periode", type: "date", defaultValue: "2026-07-31" },
      { name: "seuil_ecart_pct", type: "number", defaultValue: "2" },
      { name: "inclure_previsionnel", type: "boolean", defaultValue: "true" },
    ],
    nodes: [
      {
        id: "wf-2-n1",
        type: "trigger",
        label: "Début de mois",
        description: "Déclenchement planifié le 1er à 05h30.",
      },
      {
        id: "wf-2-n2",
        type: "action",
        label: "Importer les écritures",
        description: "Récupération des journaux comptables du mois clos.",
        tool: "Accounting API",
      },
      {
        id: "wf-2-n3",
        type: "loop",
        label: "Pour chaque segment de revenus",
        description: "Calcule la marge et compare au budget.",
      },
      {
        id: "wf-2-n4",
        type: "condition",
        label: "Écart de marge > seuil_ecart_pct ?",
        description: "Détermine si une validation humaine est requise.",
        branches: [
          { label: "Oui", nodeIds: ["wf-2-b1", "wf-2-b2"] },
          { label: "Non", nodeIds: ["wf-2-b3"] },
        ],
      },
      {
        id: "wf-2-b1",
        type: "action",
        label: "Générer un rapport d'écart",
        description: "Détaille les postes responsables de l'écart constaté.",
        tool: "Report Builder",
      },
      {
        id: "wf-2-b2",
        type: "action",
        label: "Demander la validation du CFO",
        description: "Envoi d'une demande d'approbation bloquante.",
        tool: "Approval",
      },
      {
        id: "wf-2-b3",
        type: "action",
        label: "Valider automatiquement",
        description: "Clôture sans intervention humaine.",
        tool: null,
      },
      {
        id: "wf-2-n5",
        type: "action",
        label: "Publier la synthèse exécutive",
        description: "Dépose le document dans l'Enterprise Brain.",
        tool: "Enterprise Brain",
      },
    ],
    successRate: 89,
    avgDurationMs: 742000,
    lastRunAt: "2026-08-01T05:30:00+02:00",
    runs: [
      {
        id: "wf-2-r4",
        startedAt: "2026-08-01T05:30:00+02:00",
        finishedAt: "2026-08-01T05:42:18+02:00",
        status: "success",
        triggeredBy: "Planifié",
        durationMs: 738000,
        errorMessage: null,
        nodesExecuted: 8,
        nodesTotal: 8,
      },
      {
        id: "wf-2-r3",
        startedAt: "2026-07-01T05:30:00+02:00",
        finishedAt: "2026-07-01T05:38:02+02:00",
        status: "success",
        triggeredBy: "Planifié",
        durationMs: 482000,
        errorMessage: null,
        nodesExecuted: 8,
        nodesTotal: 8,
      },
      {
        id: "wf-2-r2",
        startedAt: "2026-06-01T05:30:00+02:00",
        finishedAt: "2026-06-01T05:33:47+02:00",
        status: "failure",
        triggeredBy: "Planifié",
        durationMs: 227000,
        errorMessage:
          "Connecteur facturation indisponible : jeton OAuth expiré depuis le 31/05 (401 Unauthorized).",
        nodesExecuted: 2,
        nodesTotal: 8,
      },
      {
        id: "wf-2-r1",
        startedAt: "2026-05-01T05:30:00+02:00",
        finishedAt: "2026-05-01T05:44:10+02:00",
        status: "success",
        triggeredBy: "Finance Agent",
        durationMs: 850000,
        errorMessage: null,
        nodesExecuted: 8,
        nodesTotal: 8,
      },
    ],
    createdAt: "2026-01-08T09:00:00+01:00",
    updatedAt: "2026-08-01T06:00:00+02:00",
  },
  {
    id: "wf-3",
    name: "Synchronisation CRM ↔ Facturation",
    description:
      "Réplique en continu les contacts, opportunités gagnées et statuts de paiement entre le CRM et l'outil de facturation.",
    status: "active",
    triggerKind: "webhook",
    scheduleExpression: null,
    agentId: "a-ops",
    relatedMissionIds: ["m-3"],
    variables: [
      { name: "webhook_secret", type: "string", defaultValue: "•••••••• (masqué)" },
      { name: "retry_max", type: "number", defaultValue: "5" },
      { name: "dry_run", type: "boolean", defaultValue: "false" },
    ],
    nodes: [
      {
        id: "wf-3-n1",
        type: "trigger",
        label: "Webhook « deal.updated »",
        description: "Reçoit les événements du CRM en temps réel.",
      },
      {
        id: "wf-3-n2",
        type: "action",
        label: "Vérifier la signature",
        description: "Contrôle HMAC de la charge utile reçue.",
        tool: "Webhook Verifier",
      },
      {
        id: "wf-3-n3",
        type: "action",
        label: "Normaliser la charge utile",
        description: "Mappe les champs vers le schéma interne NASSFLOW.",
        tool: "Data Mapper",
      },
      {
        id: "wf-3-n4",
        type: "loop",
        label: "Pour chaque enregistrement modifié",
        description: "Applique la mise à jour avec jusqu'à retry_max tentatives.",
      },
      {
        id: "wf-3-n5",
        type: "action",
        label: "Écrire dans la facturation",
        description: "Crée ou met à jour le client et ses lignes de facturation.",
        tool: "Billing API",
      },
    ],
    successRate: 93,
    avgDurationMs: 4200,
    lastRunAt: "2026-08-06T07:41:00+02:00",
    runs: [
      {
        id: "wf-3-r6",
        startedAt: "2026-08-06T07:41:00+02:00",
        finishedAt: null,
        status: "running",
        triggeredBy: "Webhook CRM",
        durationMs: null,
        errorMessage: null,
        nodesExecuted: 3,
        nodesTotal: 5,
      },
      {
        id: "wf-3-r5",
        startedAt: "2026-08-06T07:12:00+02:00",
        finishedAt: "2026-08-06T07:12:04+02:00",
        status: "success",
        triggeredBy: "Webhook CRM",
        durationMs: 4100,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
      {
        id: "wf-3-r4",
        startedAt: "2026-08-06T05:48:00+02:00",
        finishedAt: "2026-08-06T05:48:03+02:00",
        status: "success",
        triggeredBy: "Webhook CRM",
        durationMs: 3600,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
      {
        id: "wf-3-r3",
        startedAt: "2026-08-05T22:03:00+02:00",
        finishedAt: "2026-08-05T22:03:09+02:00",
        status: "failure",
        triggeredBy: "Webhook CRM",
        durationMs: 9200,
        errorMessage:
          "Signature HMAC invalide sur l'événement deal.updated (id evt_8842) — charge utile rejetée.",
        nodesExecuted: 2,
        nodesTotal: 5,
      },
      {
        id: "wf-3-r2",
        startedAt: "2026-08-05T18:22:00+02:00",
        finishedAt: "2026-08-05T18:22:05+02:00",
        status: "success",
        triggeredBy: "Webhook CRM",
        durationMs: 4800,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
      {
        id: "wf-3-r1",
        startedAt: "2026-08-05T11:07:00+02:00",
        finishedAt: "2026-08-05T11:07:04+02:00",
        status: "success",
        triggeredBy: "Operations Agent",
        durationMs: 4000,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
    ],
    createdAt: "2026-02-19T14:00:00+01:00",
    updatedAt: "2026-08-05T22:10:00+02:00",
  },
  {
    id: "wf-4",
    name: "Onboarding d'un nouveau collaborateur",
    description:
      "Orchestre l'accueil d'une nouvelle recrue : comptes, matériel, parcours de formation et point à J+30.",
    status: "active",
    triggerKind: "event",
    scheduleExpression: null,
    agentId: "a-hr",
    relatedMissionIds: ["m-6"],
    variables: [
      { name: "collaborateur", type: "string", defaultValue: "" },
      { name: "date_arrivee", type: "date", defaultValue: "2026-09-01" },
      { name: "teletravail", type: "boolean", defaultValue: "true" },
    ],
    nodes: [
      {
        id: "wf-4-n1",
        type: "trigger",
        label: "Événement « contrat.signé »",
        description: "Émis par le SIRH à la signature du contrat.",
      },
      {
        id: "wf-4-n2",
        type: "action",
        label: "Créer les comptes et accès",
        description: "Provisionne messagerie, SSO et outils métier.",
        tool: "Identity Provider",
      },
      {
        id: "wf-4-n3",
        type: "action",
        label: "Commander le matériel",
        description: "Génère la demande d'équipement selon le poste.",
        tool: "Procurement",
      },
      {
        id: "wf-4-n4",
        type: "loop",
        label: "Pour chaque module de formation",
        description: "Planifie les sessions du parcours d'intégration.",
      },
      {
        id: "wf-4-n5",
        type: "action",
        label: "Programmer le point J+30",
        description: "Crée l'entretien de suivi avec le manager.",
        tool: "Calendar",
      },
    ],
    successRate: 98,
    avgDurationMs: 61000,
    lastRunAt: "2026-07-28T09:15:00+02:00",
    runs: [
      {
        id: "wf-4-r4",
        startedAt: "2026-07-28T09:15:00+02:00",
        finishedAt: "2026-07-28T09:16:02+02:00",
        status: "success",
        triggeredBy: "HR Agent",
        durationMs: 62000,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
      {
        id: "wf-4-r3",
        startedAt: "2026-07-14T10:02:00+02:00",
        finishedAt: "2026-07-14T10:03:00+02:00",
        status: "success",
        triggeredBy: "HR Agent",
        durationMs: 60000,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
      {
        id: "wf-4-r2",
        startedAt: "2026-06-30T08:45:00+02:00",
        finishedAt: "2026-06-30T08:45:26+02:00",
        status: "failure",
        triggeredBy: "Événement contrat.signé",
        durationMs: 26000,
        errorMessage:
          "Création du compte SSO refusée : licence indisponible sur le tenant (code LIC_EXHAUSTED).",
        nodesExecuted: 1,
        nodesTotal: 5,
      },
      {
        id: "wf-4-r1",
        startedAt: "2026-06-02T09:00:00+02:00",
        finishedAt: "2026-06-02T09:01:04+02:00",
        status: "success",
        triggeredBy: "Déclenchement manuel",
        durationMs: 64000,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
    ],
    createdAt: "2026-01-22T11:00:00+01:00",
    updatedAt: "2026-07-28T09:20:00+02:00",
  },
  {
    id: "wf-5",
    name: "Escalade des tickets support critiques",
    description:
      "Analyse les tickets entrants, détecte l'urgence et escalade vers un humain lorsque le SLA est menacé.",
    status: "error",
    triggerKind: "event",
    scheduleExpression: null,
    agentId: "a-support",
    relatedMissionIds: ["m-4"],
    variables: [
      { name: "sla_minutes", type: "number", defaultValue: "60" },
      { name: "canal_escalade", type: "string", defaultValue: "#support-urgent" },
    ],
    nodes: [
      {
        id: "wf-5-n1",
        type: "trigger",
        label: "Événement « ticket.créé »",
        description: "Chaque nouveau ticket entrant déclenche le workflow.",
      },
      {
        id: "wf-5-n2",
        type: "action",
        label: "Classifier le ticket",
        description: "Détermine catégorie, sentiment et criticité.",
        tool: "LLM Classifier",
      },
      {
        id: "wf-5-n3",
        type: "condition",
        label: "Criticité « haute » ou SLA < sla_minutes ?",
        description: "Choisit entre escalade humaine et réponse automatique.",
        branches: [
          { label: "Oui", nodeIds: ["wf-5-b1", "wf-5-b2"] },
          { label: "Non", nodeIds: ["wf-5-b3"] },
        ],
      },
      {
        id: "wf-5-b1",
        type: "action",
        label: "Alerter l'équipe support",
        description: "Publie une alerte sur canal_escalade.",
        tool: "Slack",
      },
      {
        id: "wf-5-b2",
        type: "action",
        label: "Réassigner à un agent humain",
        description: "Transfère le ticket avec le contexte complet.",
        tool: "Helpdesk API",
      },
      {
        id: "wf-5-b3",
        type: "action",
        label: "Répondre depuis la Enterprise Brain",
        description: "Réponse générée à partir de l'Enterprise Brain.",
        tool: "Enterprise Brain",
      },
    ],
    successRate: 71,
    avgDurationMs: 18500,
    lastRunAt: "2026-08-06T04:22:00+02:00",
    runs: [
      {
        id: "wf-5-r5",
        startedAt: "2026-08-06T04:22:00+02:00",
        finishedAt: "2026-08-06T04:22:11+02:00",
        status: "failure",
        triggeredBy: "Événement ticket.créé",
        durationMs: 11000,
        errorMessage:
          "Helpdesk API injoignable : délai d'attente dépassé après 10 s (ETIMEDOUT) — ticket non réassigné.",
        nodesExecuted: 4,
        nodesTotal: 6,
      },
      {
        id: "wf-5-r4",
        startedAt: "2026-08-06T02:10:00+02:00",
        finishedAt: "2026-08-06T02:10:09+02:00",
        status: "failure",
        triggeredBy: "Événement ticket.créé",
        durationMs: 9000,
        errorMessage: "Helpdesk API injoignable : délai d'attente dépassé après 10 s (ETIMEDOUT).",
        nodesExecuted: 4,
        nodesTotal: 6,
      },
      {
        id: "wf-5-r3",
        startedAt: "2026-08-05T19:35:00+02:00",
        finishedAt: "2026-08-05T19:35:18+02:00",
        status: "success",
        triggeredBy: "Événement ticket.créé",
        durationMs: 18000,
        errorMessage: null,
        nodesExecuted: 6,
        nodesTotal: 6,
      },
      {
        id: "wf-5-r2",
        startedAt: "2026-08-05T15:12:00+02:00",
        finishedAt: "2026-08-05T15:12:21+02:00",
        status: "success",
        triggeredBy: "Support Agent",
        durationMs: 21000,
        errorMessage: null,
        nodesExecuted: 6,
        nodesTotal: 6,
      },
      {
        id: "wf-5-r1",
        startedAt: "2026-08-05T09:04:00+02:00",
        finishedAt: "2026-08-05T09:04:19+02:00",
        status: "success",
        triggeredBy: "Événement ticket.créé",
        durationMs: 19000,
        errorMessage: null,
        nodesExecuted: 6,
        nodesTotal: 6,
      },
    ],
    createdAt: "2026-04-03T13:30:00+02:00",
    updatedAt: "2026-08-06T04:25:00+02:00",
  },
  {
    id: "wf-6",
    name: "Publication de campagne multicanale",
    description:
      "Publie les contenus validés sur les canaux marketing, planifie les relances et remonte les métriques.",
    status: "paused",
    triggerKind: "manual",
    scheduleExpression: null,
    agentId: "a-marketing",
    relatedMissionIds: ["m-7"],
    variables: [
      { name: "campagne", type: "string", defaultValue: "Q3-Acquisition" },
      { name: "budget_max", type: "number", defaultValue: "15000" },
      { name: "date_lancement", type: "date", defaultValue: "2026-09-08" },
    ],
    nodes: [
      {
        id: "wf-6-n1",
        type: "trigger",
        label: "Lancement manuel",
        description: "Déclenché par le Marketing Agent après validation.",
      },
      {
        id: "wf-6-n2",
        type: "loop",
        label: "Pour chaque canal de diffusion",
        description: "LinkedIn, e-mailing, blog et publicité display.",
      },
      {
        id: "wf-6-n3",
        type: "action",
        label: "Publier le contenu",
        description: "Adapte le format au canal puis publie.",
        tool: "Social Publisher",
      },
      {
        id: "wf-6-n4",
        type: "action",
        label: "Collecter les métriques à J+3",
        description: "Impressions, clics et coût par acquisition.",
        tool: "Analytics",
      },
    ],
    successRate: 84,
    avgDurationMs: 96000,
    lastRunAt: "2026-07-19T14:00:00+02:00",
    runs: [
      {
        id: "wf-6-r4",
        startedAt: "2026-07-19T14:00:00+02:00",
        finishedAt: "2026-07-19T14:01:38+02:00",
        status: "success",
        triggeredBy: "Déclenchement manuel",
        durationMs: 98000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
      {
        id: "wf-6-r3",
        startedAt: "2026-07-05T10:30:00+02:00",
        finishedAt: "2026-07-05T10:31:12+02:00",
        status: "success",
        triggeredBy: "Marketing Agent",
        durationMs: 72000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
      {
        id: "wf-6-r2",
        startedAt: "2026-06-21T09:00:00+02:00",
        finishedAt: "2026-06-21T09:00:42+02:00",
        status: "failure",
        triggeredBy: "Déclenchement manuel",
        durationMs: 42000,
        errorMessage:
          "Publication LinkedIn refusée : le visuel dépasse la taille maximale autorisée (8 Mo).",
        nodesExecuted: 3,
        nodesTotal: 4,
      },
      {
        id: "wf-6-r1",
        startedAt: "2026-06-07T11:15:00+02:00",
        finishedAt: "2026-06-07T11:16:30+02:00",
        status: "success",
        triggeredBy: "Marketing Agent",
        durationMs: 90000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
    ],
    createdAt: "2026-03-30T15:00:00+02:00",
    updatedAt: "2026-07-24T09:00:00+02:00",
  },
  {
    id: "wf-7",
    name: "Veille concurrentielle hebdomadaire",
    description:
      "Collecte les signaux publics sur les concurrents, résume les évolutions et alimente l'Enterprise Brain.",
    status: "active",
    triggerKind: "scheduled",
    scheduleExpression: "Chaque lundi à 07h00",
    agentId: "a-ceo",
    relatedMissionIds: ["m-5"],
    variables: [
      { name: "concurrents", type: "string", defaultValue: "5 sociétés suivies" },
      { name: "profondeur_jours", type: "number", defaultValue: "7" },
    ],
    nodes: [
      {
        id: "wf-7-n1",
        type: "trigger",
        label: "Planification hebdomadaire",
        description: "Chaque lundi matin avant le comité de direction.",
      },
      {
        id: "wf-7-n2",
        type: "loop",
        label: "Pour chaque concurrent suivi",
        description: "Parcourt les sources publiques configurées.",
      },
      {
        id: "wf-7-n3",
        type: "action",
        label: "Collecter et dédupliquer",
        description: "Agrège les articles, communiqués et offres d'emploi.",
        tool: "Web Search",
      },
      {
        id: "wf-7-n4",
        type: "action",
        label: "Synthétiser les signaux",
        description: "Produit un résumé priorisé pour le comité.",
        tool: "LLM Summarizer",
      },
      {
        id: "wf-7-n5",
        type: "action",
        label: "Archiver dans l'Enterprise Brain",
        description: "Crée une note de veille datée.",
        tool: "Enterprise Brain",
      },
    ],
    successRate: 91,
    avgDurationMs: 310000,
    lastRunAt: "2026-08-03T07:00:00+02:00",
    runs: [
      {
        id: "wf-7-r4",
        startedAt: "2026-08-03T07:00:00+02:00",
        finishedAt: "2026-08-03T07:05:20+02:00",
        status: "success",
        triggeredBy: "Planifié",
        durationMs: 320000,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
      {
        id: "wf-7-r3",
        startedAt: "2026-07-27T07:00:00+02:00",
        finishedAt: "2026-07-27T07:04:41+02:00",
        status: "success",
        triggeredBy: "Planifié",
        durationMs: 281000,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
      {
        id: "wf-7-r2",
        startedAt: "2026-07-20T07:00:00+02:00",
        finishedAt: "2026-07-20T07:01:55+02:00",
        status: "failure",
        triggeredBy: "Planifié",
        durationMs: 115000,
        errorMessage:
          "Source de veille bloquée (403 Forbidden) : robots.txt interdit l'exploration du domaine.",
        nodesExecuted: 3,
        nodesTotal: 5,
      },
      {
        id: "wf-7-r1",
        startedAt: "2026-07-13T07:00:00+02:00",
        finishedAt: "2026-07-13T07:05:33+02:00",
        status: "success",
        triggeredBy: "CEO Agent",
        durationMs: 333000,
        errorMessage: null,
        nodesExecuted: 5,
        nodesTotal: 5,
      },
    ],
    createdAt: "2026-02-02T08:00:00+01:00",
    updatedAt: "2026-08-03T07:10:00+02:00",
  },
  {
    id: "wf-8",
    name: "Contrôle de conformité des dépenses",
    description:
      "Vérifie chaque note de frais soumise contre la politique de dépenses et bloque les cas non conformes.",
    status: "paused",
    triggerKind: "webhook",
    scheduleExpression: null,
    agentId: "a-finance",
    relatedMissionIds: [],
    variables: [
      { name: "plafond_repas", type: "number", defaultValue: "35" },
      { name: "justificatif_requis", type: "boolean", defaultValue: "true" },
    ],
    nodes: [
      {
        id: "wf-8-n1",
        type: "trigger",
        label: "Webhook « note_de_frais.soumise »",
        description: "Émis par l'outil de gestion des dépenses.",
      },
      {
        id: "wf-8-n2",
        type: "action",
        label: "Extraire les lignes de dépense",
        description: "Lecture OCR des justificatifs joints.",
        tool: "OCR",
      },
      {
        id: "wf-8-n3",
        type: "action",
        label: "Comparer à la politique de dépenses",
        description: "Croise chaque ligne avec les règles publiées.",
        tool: "Enterprise Brain",
      },
      {
        id: "wf-8-n4",
        type: "action",
        label: "Notifier le collaborateur",
        description: "Confirmation ou demande de correction motivée.",
        tool: "Email",
      },
    ],
    successRate: 88,
    avgDurationMs: 12500,
    lastRunAt: "2026-07-16T16:44:00+02:00",
    runs: [
      {
        id: "wf-8-r4",
        startedAt: "2026-07-16T16:44:00+02:00",
        finishedAt: "2026-07-16T16:44:14+02:00",
        status: "success",
        triggeredBy: "Webhook dépenses",
        durationMs: 14000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
      {
        id: "wf-8-r3",
        startedAt: "2026-07-16T11:20:00+02:00",
        finishedAt: "2026-07-16T11:20:11+02:00",
        status: "success",
        triggeredBy: "Webhook dépenses",
        durationMs: 11000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
      {
        id: "wf-8-r2",
        startedAt: "2026-07-15T09:05:00+02:00",
        finishedAt: "2026-07-15T09:05:06+02:00",
        status: "failure",
        triggeredBy: "Webhook dépenses",
        durationMs: 6000,
        errorMessage:
          "Justificatif illisible : la lecture OCR a échoué avec un score de confiance de 0,21.",
        nodesExecuted: 2,
        nodesTotal: 4,
      },
      {
        id: "wf-8-r1",
        startedAt: "2026-07-14T17:30:00+02:00",
        finishedAt: "2026-07-14T17:30:13+02:00",
        status: "success",
        triggeredBy: "Finance Agent",
        durationMs: 13000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
    ],
    createdAt: "2026-05-12T10:00:00+02:00",
    updatedAt: "2026-07-17T08:00:00+02:00",
  },
  {
    id: "wf-9",
    name: "Rotation des jetons d'intégration",
    description:
      "Renouvelle les jetons d'accès des connecteurs critiques avant expiration et vérifie la reprise des flux.",
    status: "draft",
    triggerKind: "scheduled",
    scheduleExpression: "Tous les 15 jours à 03h00",
    agentId: "a-ops",
    relatedMissionIds: ["m-3"],
    variables: [
      { name: "marge_expiration_jours", type: "number", defaultValue: "7" },
      { name: "notifier_securite", type: "boolean", defaultValue: "true" },
    ],
    nodes: [
      {
        id: "wf-9-n1",
        type: "trigger",
        label: "Planification bimensuelle",
        description: "Fenêtre de maintenance de nuit.",
      },
      {
        id: "wf-9-n2",
        type: "loop",
        label: "Pour chaque connecteur critique",
        description: "Parcourt les intégrations marquées comme critiques.",
      },
      {
        id: "wf-9-n3",
        type: "action",
        label: "Renouveler le jeton OAuth",
        description: "Échange le refresh token et stocke le nouveau secret.",
        tool: "Secrets Manager",
      },
      {
        id: "wf-9-n4",
        type: "action",
        label: "Rejouer une requête de contrôle",
        description: "Valide la reprise effective du flux.",
        tool: "Health Check",
      },
    ],
    successRate: 0,
    avgDurationMs: 0,
    lastRunAt: null,
    runs: [],
    createdAt: "2026-07-30T18:00:00+02:00",
    updatedAt: "2026-08-04T10:15:00+02:00",
  },
  {
    id: "wf-10",
    name: "Consolidation du reporting exécutif",
    description:
      "Agrège les KPI de tous les modules et prépare le rapport exécutif hebdomadaire du comité exécutif.",
    status: "active",
    triggerKind: "manual",
    scheduleExpression: null,
    agentId: "a-ceo",
    relatedMissionIds: ["m-5", "m-2"],
    variables: [
      { name: "periode", type: "string", defaultValue: "7 derniers jours" },
      { name: "inclure_prevision", type: "boolean", defaultValue: "true" },
    ],
    nodes: [
      {
        id: "wf-10-n1",
        type: "trigger",
        label: "Lancement manuel",
        description: "Déclenché avant le comité exécutif.",
      },
      {
        id: "wf-10-n2",
        type: "loop",
        label: "Pour chaque module source",
        description: "Missions, CRM, Workforce, Finance.",
      },
      {
        id: "wf-10-n3",
        type: "action",
        label: "Agréger les indicateurs",
        description: "Normalise et consolide les KPI collectés.",
        tool: "Analytics",
      },
      {
        id: "wf-10-n4",
        type: "action",
        label: "Produire le rapport exécutif",
        description: "Génère la vue exécutive prête à partager.",
        tool: "Report Builder",
      },
    ],
    successRate: 94,
    avgDurationMs: 128000,
    lastRunAt: "2026-08-05T17:30:00+02:00",
    runs: [
      {
        id: "wf-10-r4",
        startedAt: "2026-08-05T17:30:00+02:00",
        finishedAt: "2026-08-05T17:32:10+02:00",
        status: "success",
        triggeredBy: "Déclenchement manuel",
        durationMs: 130000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
      {
        id: "wf-10-r3",
        startedAt: "2026-07-29T17:30:00+02:00",
        finishedAt: "2026-07-29T17:32:01+02:00",
        status: "success",
        triggeredBy: "CEO Agent",
        durationMs: 121000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
      {
        id: "wf-10-r2",
        startedAt: "2026-07-22T17:30:00+02:00",
        finishedAt: "2026-07-22T17:30:48+02:00",
        status: "failure",
        triggeredBy: "Déclenchement manuel",
        durationMs: 48000,
        errorMessage:
          "Module Finance indisponible : agrégation interrompue, 2 indicateurs sur 14 manquants.",
        nodesExecuted: 2,
        nodesTotal: 4,
      },
      {
        id: "wf-10-r1",
        startedAt: "2026-07-15T17:30:00+02:00",
        finishedAt: "2026-07-15T17:32:15+02:00",
        status: "success",
        triggeredBy: "Déclenchement manuel",
        durationMs: 135000,
        errorMessage: null,
        nodesExecuted: 4,
        nodesTotal: 4,
      },
    ],
    createdAt: "2026-04-18T09:30:00+02:00",
    updatedAt: "2026-08-05T17:35:00+02:00",
  },
];

export function workflowById(id: string): Workflow | null {
  return workflowsMock.find((w) => w.id === id) ?? null;
}

export function workflowAgentById(agentId: string | null): AgentDetail | null {
  if (!agentId) return null;
  return agentsDetailMock.find((a) => a.id === agentId) ?? null;
}

export function workflowMissions(missionIds: string[]): MissionDetail[] {
  return missionIds
    .map((id) => missionsDetailMock.find((m) => m.id === id) ?? null)
    .filter((m): m is MissionDetail => m !== null);
}

/** Nombre d'exécutions démarrées sur les dernières 24h (mock, référence figée). */
export function runsLast24h(workflows: Workflow[], reference: Date): number {
  const floor = reference.getTime() - 24 * 3600 * 1000;
  return workflows.reduce(
    (total, wf) =>
      total +
      wf.runs.filter((run) => {
        const t = new Date(run.startedAt).getTime();
        return !Number.isNaN(t) && t >= floor && t <= reference.getTime();
      }).length,
    0,
  );
}