import type { MissionAgent, MissionDetail } from "./types";

/** MOCKS STATIQUES — remplaçables par une API sans toucher aux composants. */

const AG: Record<string, MissionAgent> = {
  ceo: { id: "a-ceo", name: "CEO Agent", avatar: "CE", role: "Pilotage stratégique" },
  sales: { id: "a-sales", name: "Sales Agent", avatar: "SA", role: "Développement commercial" },
  marketing: { id: "a-marketing", name: "Marketing Agent", avatar: "MA", role: "Acquisition" },
  finance: { id: "a-finance", name: "Finance Agent", avatar: "FI", role: "Analyse financière" },
  hr: { id: "a-hr", name: "HR Agent", avatar: "HR", role: "Ressources humaines" },
  support: { id: "a-support", name: "Support Agent", avatar: "SU", role: "Relation client" },
  ops: { id: "a-ops", name: "Operations Agent", avatar: "OP", role: "Opérations" },
};

export const missionAgents: MissionAgent[] = Object.values(AG);

export const missionsDetailMock: MissionDetail[] = [
  {
    id: "m-1",
    title: "Relancer les prospects inactifs",
    objective:
      "Identifier tous les prospects sans interaction depuis plus de 7 jours, segmenter par potentiel et déclencher une séquence de relance personnalisée pour réactiver le pipeline commercial.",
    priority: "high",
    status: "running",
    progress: 45,
    owner: "Nassim",
    agents: [AG["sales"]!, AG["marketing"]!],
    steps: [
      { id: "s1", title: "Extraire les prospects inactifs", status: "done", agentId: "a-sales" },
      { id: "s2", title: "Segmenter par score de potentiel", status: "done", agentId: "a-sales" },
      { id: "s3", title: "Rédiger les séquences d'e-mails", status: "running", agentId: "a-marketing" },
      { id: "s4", title: "Lancer la campagne de relance", status: "pending", agentId: "a-sales" },
    ],
    dependencies: [],
    estimatedDuration: "3 j",
    actualDuration: null,
    confidenceScore: 84,
    cost: { aiCalls: 1240, estimatedCost: "18,40 €" },
    tags: ["Commercial", "Automatisation"],
    createdAt: "2026-07-30T09:00:00.000Z",
    updatedAt: "2026-08-03T07:20:00.000Z",
    dueDate: "2026-08-05T17:00:00.000Z",
    history: [
      { timestamp: "2026-07-30T09:00:00.000Z", event: "Mission créée", actor: "Nassim" },
      { timestamp: "2026-07-30T09:12:00.000Z", event: "Agents assignés", actor: "CEO Agent" },
      { timestamp: "2026-08-03T07:20:00.000Z", event: "18 prospects relancés", actor: "Sales Agent" },
    ],
  },
  {
    id: "m-2",
    title: "Préparer le rapport financier Q3",
    objective:
      "Consolider les données comptables du trimestre, analyser l'évolution des marges par segment et produire un rapport exécutif prêt à présenter au comité de direction.",
    priority: "critical",
    status: "blocked",
    progress: 28,
    owner: "Direction financière",
    agents: [AG["finance"]!, AG["ceo"]!],
    steps: [
      { id: "s1", title: "Collecter les exports comptables", status: "done", agentId: "a-finance" },
      { id: "s2", title: "Reconnecter l'intégration facturation", status: "failed", agentId: "a-ops" },
      { id: "s3", title: "Analyser les marges par segment", status: "pending", agentId: "a-finance" },
      { id: "s4", title: "Générer la synthèse exécutive", status: "pending", agentId: "a-ceo" },
    ],
    dependencies: ["m-3"],
    estimatedDuration: "5 j",
    actualDuration: null,
    confidenceScore: 61,
    cost: { aiCalls: 860, estimatedCost: "12,10 €" },
    tags: ["Finance", "Reporting"],
    createdAt: "2026-07-28T08:30:00.000Z",
    updatedAt: "2026-08-02T15:10:00.000Z",
    dueDate: "2026-08-07T09:00:00.000Z",
    history: [
      { timestamp: "2026-07-28T08:30:00.000Z", event: "Mission créée", actor: "Nassim" },
      { timestamp: "2026-08-01T10:05:00.000Z", event: "Étape en échec : intégration facturation", actor: "Operations Agent" },
      { timestamp: "2026-08-02T15:10:00.000Z", event: "Mission bloquée", actor: "Système" },
    ],
  },
  {
    id: "m-3",
    title: "Reconnecter les intégrations critiques",
    objective:
      "Rétablir les connexions des intégrations facturation et CRM déconnectées depuis 3 jours, puis vérifier l'intégrité des synchronisations de données.",
    priority: "critical",
    status: "waiting",
    progress: 70,
    owner: "Nassim",
    agents: [AG["ops"]!, AG["support"]!],
    steps: [
      { id: "s1", title: "Diagnostiquer les connecteurs", status: "done", agentId: "a-ops" },
      { id: "s2", title: "Renouveler les jetons d'accès", status: "done", agentId: "a-ops" },
      { id: "s3", title: "Attendre la validation sécurité", status: "running", agentId: "a-support" },
      { id: "s4", title: "Rejouer la synchronisation", status: "pending", agentId: "a-ops" },
    ],
    dependencies: [],
    estimatedDuration: "1 j",
    actualDuration: null,
    confidenceScore: 77,
    cost: { aiCalls: 320, estimatedCost: "4,60 €" },
    tags: ["Sécurité", "Intégrations"],
    createdAt: "2026-08-01T06:40:00.000Z",
    updatedAt: "2026-08-03T06:55:00.000Z",
    dueDate: "2026-08-04T12:00:00.000Z",
    history: [
      { timestamp: "2026-08-01T06:40:00.000Z", event: "Mission créée", actor: "Nassim" },
      { timestamp: "2026-08-02T11:30:00.000Z", event: "Jetons renouvelés", actor: "Operations Agent" },
      { timestamp: "2026-08-03T06:55:00.000Z", event: "En attente de validation sécurité", actor: "Système" },
    ],
  },
  {
    id: "m-4",
    title: "Réduire le temps de réponse support",
    objective:
      "Mettre en place un tri automatique des tickets entrants de niveau 1 afin de ramener le temps de première réponse sous le SLA de 4 heures.",
    priority: "medium",
    status: "ready",
    progress: 0,
    owner: "Responsable Support",
    agents: [AG["support"]!],
    steps: [
      { id: "s1", title: "Cartographier les motifs de tickets", status: "pending", agentId: "a-support" },
      { id: "s2", title: "Définir les règles de tri", status: "pending", agentId: "a-support" },
      { id: "s3", title: "Activer le tri automatique", status: "pending", agentId: "a-ops" },
    ],
    dependencies: [],
    estimatedDuration: "6 j",
    actualDuration: null,
    confidenceScore: 72,
    cost: { aiCalls: 0, estimatedCost: "0,00 €" },
    tags: ["Support", "SLA"],
    createdAt: "2026-08-02T14:00:00.000Z",
    updatedAt: "2026-08-02T14:20:00.000Z",
    dueDate: "2026-08-12T17:00:00.000Z",
    history: [
      { timestamp: "2026-08-02T14:00:00.000Z", event: "Mission créée", actor: "Nassim" },
      { timestamp: "2026-08-02T14:20:00.000Z", event: "Mission prête à démarrer", actor: "CEO Agent" },
    ],
  },
  {
    id: "m-5",
    title: "Consolider le reporting exécutif",
    objective:
      "Unifier les sources de reporting commercial, financier et opérationnel dans une synthèse hebdomadaire unique destinée à la direction.",
    priority: "low",
    status: "completed",
    progress: 100,
    owner: "Nassim",
    agents: [AG["ceo"]!, AG["finance"]!],
    steps: [
      { id: "s1", title: "Inventorier les sources", status: "done", agentId: "a-ceo" },
      { id: "s2", title: "Normaliser les indicateurs", status: "done", agentId: "a-finance" },
      { id: "s3", title: "Publier la synthèse hebdomadaire", status: "done", agentId: "a-ceo" },
    ],
    dependencies: [],
    estimatedDuration: "4 j",
    actualDuration: "3 j 6 h",
    confidenceScore: 93,
    cost: { aiCalls: 2140, estimatedCost: "29,80 €" },
    tags: ["Pilotage", "Reporting"],
    createdAt: "2026-07-25T08:00:00.000Z",
    updatedAt: "2026-08-01T17:40:00.000Z",
    dueDate: "2026-08-01T17:00:00.000Z",
    history: [
      { timestamp: "2026-07-25T08:00:00.000Z", event: "Mission créée", actor: "Nassim" },
      { timestamp: "2026-08-01T17:40:00.000Z", event: "Mission terminée", actor: "CEO Agent" },
    ],
  },
  {
    id: "m-6",
    title: "Structurer le plan de recrutement H2",
    objective:
      "Analyser la charge des équipes, prioriser les postes à ouvrir au second semestre et préparer les fiches de poste correspondantes.",
    priority: "medium",
    status: "draft",
    progress: 0,
    owner: "Direction RH",
    agents: [AG["hr"]!],
    steps: [
      { id: "s1", title: "Analyser la charge par équipe", status: "pending", agentId: "a-hr" },
      { id: "s2", title: "Prioriser les ouvertures de postes", status: "pending", agentId: "a-hr" },
    ],
    dependencies: [],
    estimatedDuration: "8 j",
    actualDuration: null,
    confidenceScore: 54,
    cost: { aiCalls: 0, estimatedCost: "0,00 €" },
    tags: ["RH", "Planification"],
    createdAt: "2026-08-03T06:10:00.000Z",
    updatedAt: "2026-08-03T06:10:00.000Z",
    dueDate: "2026-08-20T17:00:00.000Z",
    history: [{ timestamp: "2026-08-03T06:10:00.000Z", event: "Brouillon créé", actor: "Nassim" }],
  },
  {
    id: "m-7",
    title: "Lancer la campagne marketing Q3",
    objective:
      "Concevoir et diffuser la campagne d'acquisition du trimestre sur les canaux e-mail et social, avec un budget maîtrisé et un suivi de performance quotidien.",
    priority: "high",
    status: "failed",
    progress: 38,
    owner: "Direction Marketing",
    agents: [AG["marketing"]!, AG["sales"]!],
    steps: [
      { id: "s1", title: "Définir les segments cibles", status: "done", agentId: "a-marketing" },
      { id: "s2", title: "Produire les créations", status: "failed", agentId: "a-marketing" },
      { id: "s3", title: "Diffuser la campagne", status: "pending", agentId: "a-marketing" },
    ],
    dependencies: ["m-2"],
    estimatedDuration: "7 j",
    actualDuration: "2 j 4 h",
    confidenceScore: 38,
    cost: { aiCalls: 640, estimatedCost: "9,20 €" },
    tags: ["Marketing", "Acquisition"],
    createdAt: "2026-07-27T10:00:00.000Z",
    updatedAt: "2026-07-31T16:30:00.000Z",
    dueDate: "2026-08-06T12:00:00.000Z",
    history: [
      { timestamp: "2026-07-27T10:00:00.000Z", event: "Mission créée", actor: "Nassim" },
      { timestamp: "2026-07-31T16:30:00.000Z", event: "Échec : budget créatif indisponible", actor: "Marketing Agent" },
    ],
  },
  {
    id: "m-8",
    title: "Migrer la facturation vers le nouveau prestataire",
    objective:
      "Basculer l'ensemble des contrats de facturation vers le nouveau prestataire cloud et vérifier la conformité des données transférées.",
    priority: "high",
    status: "cancelled",
    progress: 15,
    owner: "Direction financière",
    agents: [AG["finance"]!, AG["ops"]!],
    steps: [
      { id: "s1", title: "Auditer les contrats existants", status: "done", agentId: "a-finance" },
      { id: "s2", title: "Préparer la migration", status: "pending", agentId: "a-ops" },
    ],
    dependencies: [],
    estimatedDuration: "12 j",
    actualDuration: "1 j 2 h",
    confidenceScore: 45,
    cost: { aiCalls: 180, estimatedCost: "2,70 €" },
    tags: ["Finance", "Migration"],
    createdAt: "2026-07-20T09:00:00.000Z",
    updatedAt: "2026-07-29T11:00:00.000Z",
    dueDate: "2026-08-15T17:00:00.000Z",
    history: [
      { timestamp: "2026-07-20T09:00:00.000Z", event: "Mission créée", actor: "Nassim" },
      { timestamp: "2026-07-29T11:00:00.000Z", event: "Mission annulée — renégociation en cours", actor: "Nassim" },
    ],
  },
  {
    id: "m-9",
    title: "Audit de sécurité des accès agents",
    objective:
      "Passer en revue les permissions accordées à chaque agent IA, retirer les accès superflus et documenter la matrice de droits.",
    priority: "low",
    status: "archived",
    progress: 100,
    owner: "Nassim",
    agents: [AG["ops"]!, AG["ceo"]!],
    steps: [
      { id: "s1", title: "Extraire la matrice des accès", status: "done", agentId: "a-ops" },
      { id: "s2", title: "Retirer les accès superflus", status: "done", agentId: "a-ops" },
    ],
    dependencies: [],
    estimatedDuration: "2 j",
    actualDuration: "1 j 8 h",
    confidenceScore: 88,
    cost: { aiCalls: 410, estimatedCost: "5,90 €" },
    tags: ["Sécurité", "Conformité"],
    createdAt: "2026-07-10T08:00:00.000Z",
    updatedAt: "2026-07-15T17:00:00.000Z",
    dueDate: "2026-07-15T17:00:00.000Z",
    history: [
      { timestamp: "2026-07-10T08:00:00.000Z", event: "Mission créée", actor: "Nassim" },
      { timestamp: "2026-07-15T17:00:00.000Z", event: "Mission archivée", actor: "Système" },
    ],
  },
  {
    id: "m-10",
    title: "Identifier les upsells sur les comptes clés",
    objective:
      "Détecter les comptes dont l'usage dépasse 90% du quota et préparer une proposition d'extension commerciale personnalisée pour chacun.",
    priority: "high",
    status: "running",
    progress: 62,
    owner: "Direction commerciale",
    agents: [AG["sales"]!, AG["ceo"]!],
    steps: [
      { id: "s1", title: "Analyser l'usage produit", status: "done", agentId: "a-sales" },
      { id: "s2", title: "Chiffrer les propositions", status: "running", agentId: "a-finance" },
      { id: "s3", title: "Préparer les rendez-vous", status: "pending", agentId: "a-sales" },
    ],
    dependencies: ["m-1"],
    estimatedDuration: "4 j",
    actualDuration: null,
    confidenceScore: 81,
    cost: { aiCalls: 970, estimatedCost: "13,50 €" },
    tags: ["Commercial", "Upsell"],
    createdAt: "2026-07-31T09:30:00.000Z",
    updatedAt: "2026-08-03T06:00:00.000Z",
    dueDate: "2026-08-08T17:00:00.000Z",
    history: [
      { timestamp: "2026-07-31T09:30:00.000Z", event: "Mission créée", actor: "CEO Agent" },
      { timestamp: "2026-08-03T06:00:00.000Z", event: "8 comptes qualifiés", actor: "Sales Agent" },
    ],
  },
];