/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SystemSettingsRouteImport } from './routes/system-settings'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmContactIdRouteImport } from './routes/crm.$contactId'
import { Route as EnterpriseBrainIndexRouteImport } from './routes/enterprise-brain.index'
import { Route as EnterpriseBrainItemIdRouteImport } from './routes/enterprise-brain.$itemId'
import { Route as IntegrationsHubIndexRouteImport } from './routes/integrations-hub.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as MissionsMissionIdRouteImport } from './routes/missions.$missionId'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as OrganizationMemberIdRouteImport } from './routes/organization.$memberId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as WorkflowEngineIndexRouteImport } from './routes/workflow-engine.index'
import { Route as WorkflowEngineWorkflowIdRouteImport } from './routes/workflow-engine.$workflowId'
import { Route as SettingsMembersMemberIdRouteImport } from './routes/settings.members.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactIdRoute = CrmContactIdRouteImport.update({
  id: '/crm/$contactId',
  path: '/crm/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseBrainIndexRoute = EnterpriseBrainIndexRouteImport.update({
  id: '/enterprise-brain/',
  path: '/enterprise-brain/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseBrainItemIdRoute = EnterpriseBrainItemIdRouteImport.update({
  id: '/enterprise-brain/$itemId',
  path: '/enterprise-brain/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsHubIndexRoute = IntegrationsHubIndexRouteImport.update({
  id: '/integrations-hub/',
  path: '/integrations-hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdRoute = MissionsMissionIdRouteImport.update({
  id: '/missions/$missionId',
  path: '/missions/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationMemberIdRoute = OrganizationMemberIdRouteImport.update({
  id: '/organization/$memberId',
  path: '/organization/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowEngineIndexRoute = WorkflowEngineIndexRouteImport.update({
  id: '/workflow-engine/',
  path: '/workflow-engine/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowEngineWorkflowIdRoute =
  WorkflowEngineWorkflowIdRouteImport.update({
    id: '/workflow-engine/$workflowId',
    path: '/workflow-engine/$workflowId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsMembersMemberIdRoute = SettingsMembersMemberIdRouteImport.update({
  id: '/settings/members/$memberId',
  path: '/settings/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-settings': typeof SystemSettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/crm/$contactId': typeof CrmContactIdRoute
  '/enterprise-brain/$itemId': typeof EnterpriseBrainItemIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/organization/$memberId': typeof OrganizationMemberIdRoute
  '/workflow-engine/$workflowId': typeof WorkflowEngineWorkflowIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/enterprise-brain/': typeof EnterpriseBrainIndexRoute
  '/integrations-hub/': typeof IntegrationsHubIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflow-engine/': typeof WorkflowEngineIndexRoute
  '/settings/members/$memberId': typeof SettingsMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-settings': typeof SystemSettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/crm/$contactId': typeof CrmContactIdRoute
  '/enterprise-brain/$itemId': typeof EnterpriseBrainItemIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/organization/$memberId': typeof OrganizationMemberIdRoute
  '/workflow-engine/$workflowId': typeof WorkflowEngineWorkflowIdRoute
  '/agents': typeof AgentsIndexRoute
  '/crm': typeof CrmIndexRoute
  '/enterprise-brain': typeof EnterpriseBrainIndexRoute
  '/integrations-hub': typeof IntegrationsHubIndexRoute
  '/missions': typeof MissionsIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workflow-engine': typeof WorkflowEngineIndexRoute
  '/settings/members/$memberId': typeof SettingsMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-settings': typeof SystemSettingsRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/crm/$contactId': typeof CrmContactIdRoute
  '/enterprise-brain/$itemId': typeof EnterpriseBrainItemIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/organization/$memberId': typeof OrganizationMemberIdRoute
  '/workflow-engine/$workflowId': typeof WorkflowEngineWorkflowIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/enterprise-brain/': typeof EnterpriseBrainIndexRoute
  '/integrations-hub/': typeof IntegrationsHubIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workflow-engine/': typeof WorkflowEngineIndexRoute
  '/settings/members/$memberId': typeof SettingsMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/system-settings'
    | '/agents/$agentId'
    | '/crm/$contactId'
    | '/enterprise-brain/$itemId'
    | '/invite/$token'
    | '/missions/$missionId'
    | '/organization/$memberId'
    | '/workflow-engine/$workflowId'
    | '/agents/'
    | '/crm/'
    | '/enterprise-brain/'
    | '/integrations-hub/'
    | '/missions/'
    | '/organization/'
    | '/settings/'
    | '/workflow-engine/'
    | '/settings/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/system-settings'
    | '/agents/$agentId'
    | '/crm/$contactId'
    | '/enterprise-brain/$itemId'
    | '/invite/$token'
    | '/missions/$missionId'
    | '/organization/$memberId'
    | '/workflow-engine/$workflowId'
    | '/agents'
    | '/crm'
    | '/enterprise-brain'
    | '/integrations-hub'
    | '/missions'
    | '/organization'
    | '/settings'
    | '/workflow-engine'
    | '/settings/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/system-settings'
    | '/agents/$agentId'
    | '/crm/$contactId'
    | '/enterprise-brain/$itemId'
    | '/invite/$token'
    | '/missions/$missionId'
    | '/organization/$memberId'
    | '/workflow-engine/$workflowId'
    | '/agents/'
    | '/crm/'
    | '/enterprise-brain/'
    | '/integrations-hub/'
    | '/missions/'
    | '/organization/'
    | '/settings/'
    | '/workflow-engine/'
    | '/settings/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SystemSettingsRoute: typeof SystemSettingsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  CrmContactIdRoute: typeof CrmContactIdRoute
  EnterpriseBrainItemIdRoute: typeof EnterpriseBrainItemIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MissionsMissionIdRoute: typeof MissionsMissionIdRoute
  OrganizationMemberIdRoute: typeof OrganizationMemberIdRoute
  WorkflowEngineWorkflowIdRoute: typeof WorkflowEngineWorkflowIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CrmIndexRoute: typeof CrmIndexRoute
  EnterpriseBrainIndexRoute: typeof EnterpriseBrainIndexRoute
  IntegrationsHubIndexRoute: typeof IntegrationsHubIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  WorkflowEngineIndexRoute: typeof WorkflowEngineIndexRoute
  SettingsMembersMemberIdRoute: typeof SettingsMembersMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-settings': {
      id: '/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/$contactId': {
      id: '/crm/$contactId'
      path: '/crm/$contactId'
      fullPath: '/crm/$contactId'
      preLoaderRoute: typeof CrmContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-brain/': {
      id: '/enterprise-brain/'
      path: '/enterprise-brain'
      fullPath: '/enterprise-brain/'
      preLoaderRoute: typeof EnterpriseBrainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-brain/$itemId': {
      id: '/enterprise-brain/$itemId'
      path: '/enterprise-brain/$itemId'
      fullPath: '/enterprise-brain/$itemId'
      preLoaderRoute: typeof EnterpriseBrainItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations-hub/': {
      id: '/integrations-hub/'
      path: '/integrations-hub'
      fullPath: '/integrations-hub/'
      preLoaderRoute: typeof IntegrationsHubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId': {
      id: '/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof MissionsMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$memberId': {
      id: '/organization/$memberId'
      path: '/organization/$memberId'
      fullPath: '/organization/$memberId'
      preLoaderRoute: typeof OrganizationMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-engine/': {
      id: '/workflow-engine/'
      path: '/workflow-engine'
      fullPath: '/workflow-engine/'
      preLoaderRoute: typeof WorkflowEngineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-engine/$workflowId': {
      id: '/workflow-engine/$workflowId'
      path: '/workflow-engine/$workflowId'
      fullPath: '/workflow-engine/$workflowId'
      preLoaderRoute: typeof WorkflowEngineWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/members/$memberId': {
      id: '/settings/members/$memberId'
      path: '/settings/members/$memberId'
      fullPath: '/settings/members/$memberId'
      preLoaderRoute: typeof SettingsMembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SystemSettingsRoute: SystemSettingsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  CrmContactIdRoute: CrmContactIdRoute,
  EnterpriseBrainItemIdRoute: EnterpriseBrainItemIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  MissionsMissionIdRoute: MissionsMissionIdRoute,
  OrganizationMemberIdRoute: OrganizationMemberIdRoute,
  WorkflowEngineWorkflowIdRoute: WorkflowEngineWorkflowIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CrmIndexRoute: CrmIndexRoute,
  EnterpriseBrainIndexRoute: EnterpriseBrainIndexRoute,
  IntegrationsHubIndexRoute: IntegrationsHubIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  WorkflowEngineIndexRoute: WorkflowEngineIndexRoute,
  SettingsMembersMemberIdRoute: SettingsMembersMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
