/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as IntegrationsHubIndexRouteImport } from './routes/integrations-hub.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as MissionsMissionIdRouteImport } from './routes/missions.$missionId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsMembersMemberIdRouteImport } from './routes/settings.members.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsHubIndexRoute = IntegrationsHubIndexRouteImport.update({
  id: '/integrations-hub/',
  path: '/integrations-hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdRoute = MissionsMissionIdRouteImport.update({
  id: '/missions/$missionId',
  path: '/missions/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMembersMemberIdRoute = SettingsMembersMemberIdRouteImport.update({
  id: '/settings/members/$memberId',
  path: '/settings/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/integrations-hub/': typeof IntegrationsHubIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/members/$memberId': typeof SettingsMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/agents': typeof AgentsIndexRoute
  '/integrations-hub': typeof IntegrationsHubIndexRoute
  '/missions': typeof MissionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/members/$memberId': typeof SettingsMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/integrations-hub/': typeof IntegrationsHubIndexRoute
  '/missions/': typeof MissionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/members/$memberId': typeof SettingsMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/agents/$agentId'
    | '/invite/$token'
    | '/missions/$missionId'
    | '/agents/'
    | '/integrations-hub/'
    | '/missions/'
    | '/settings/'
    | '/settings/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/agents/$agentId'
    | '/invite/$token'
    | '/missions/$missionId'
    | '/agents'
    | '/integrations-hub'
    | '/missions'
    | '/settings'
    | '/settings/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/agents/$agentId'
    | '/invite/$token'
    | '/missions/$missionId'
    | '/agents/'
    | '/integrations-hub/'
    | '/missions/'
    | '/settings/'
    | '/settings/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MissionsMissionIdRoute: typeof MissionsMissionIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  IntegrationsHubIndexRoute: typeof IntegrationsHubIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsMembersMemberIdRoute: typeof SettingsMembersMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations-hub/': {
      id: '/integrations-hub/'
      path: '/integrations-hub'
      fullPath: '/integrations-hub/'
      preLoaderRoute: typeof IntegrationsHubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId': {
      id: '/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof MissionsMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/members/$memberId': {
      id: '/settings/members/$memberId'
      path: '/settings/members/$memberId'
      fullPath: '/settings/members/$memberId'
      preLoaderRoute: typeof SettingsMembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  MissionsMissionIdRoute: MissionsMissionIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  IntegrationsHubIndexRoute: IntegrationsHubIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsMembersMemberIdRoute: SettingsMembersMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
