/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntegrationsHubRouteImport } from './routes/integrations-hub'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as SecurityCenterRouteImport } from './routes/security-center'
import { Route as SystemSettingsRouteImport } from './routes/system-settings'
import { Route as WorkflowEngineRouteImport } from './routes/workflow-engine'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmContactIdRouteImport } from './routes/crm.$contactId'
import { Route as EnterpriseBrainIndexRouteImport } from './routes/enterprise-brain.index'
import { Route as EnterpriseBrainItemIdRouteImport } from './routes/enterprise-brain.$itemId'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as MissionsMissionIdRouteImport } from './routes/missions.$missionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsHubRoute = IntegrationsHubRouteImport.update({
  id: '/integrations-hub',
  path: '/integrations-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCenterRoute = SecurityCenterRouteImport.update({
  id: '/security-center',
  path: '/security-center',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSettingsRoute = SystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowEngineRoute = WorkflowEngineRouteImport.update({
  id: '/workflow-engine',
  path: '/workflow-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactIdRoute = CrmContactIdRouteImport.update({
  id: '/crm/$contactId',
  path: '/crm/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseBrainIndexRoute = EnterpriseBrainIndexRouteImport.update({
  id: '/enterprise-brain/',
  path: '/enterprise-brain/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseBrainItemIdRoute = EnterpriseBrainItemIdRouteImport.update({
  id: '/enterprise-brain/$itemId',
  path: '/enterprise-brain/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdRoute = MissionsMissionIdRouteImport.update({
  id: '/missions/$missionId',
  path: '/missions/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/help-center': typeof HelpCenterRoute
  '/insights': typeof InsightsRoute
  '/integrations-hub': typeof IntegrationsHubRoute
  '/organization': typeof OrganizationRoute
  '/security-center': typeof SecurityCenterRoute
  '/system-settings': typeof SystemSettingsRoute
  '/workflow-engine': typeof WorkflowEngineRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/crm/$contactId': typeof CrmContactIdRoute
  '/enterprise-brain/$itemId': typeof EnterpriseBrainItemIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/enterprise-brain/': typeof EnterpriseBrainIndexRoute
  '/missions/': typeof MissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/help-center': typeof HelpCenterRoute
  '/insights': typeof InsightsRoute
  '/integrations-hub': typeof IntegrationsHubRoute
  '/organization': typeof OrganizationRoute
  '/security-center': typeof SecurityCenterRoute
  '/system-settings': typeof SystemSettingsRoute
  '/workflow-engine': typeof WorkflowEngineRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/crm/$contactId': typeof CrmContactIdRoute
  '/enterprise-brain/$itemId': typeof EnterpriseBrainItemIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/agents': typeof AgentsIndexRoute
  '/crm': typeof CrmIndexRoute
  '/enterprise-brain': typeof EnterpriseBrainIndexRoute
  '/missions': typeof MissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/help-center': typeof HelpCenterRoute
  '/insights': typeof InsightsRoute
  '/integrations-hub': typeof IntegrationsHubRoute
  '/organization': typeof OrganizationRoute
  '/security-center': typeof SecurityCenterRoute
  '/system-settings': typeof SystemSettingsRoute
  '/workflow-engine': typeof WorkflowEngineRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/crm/$contactId': typeof CrmContactIdRoute
  '/enterprise-brain/$itemId': typeof EnterpriseBrainItemIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/enterprise-brain/': typeof EnterpriseBrainIndexRoute
  '/missions/': typeof MissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/help-center'
    | '/insights'
    | '/integrations-hub'
    | '/organization'
    | '/security-center'
    | '/system-settings'
    | '/workflow-engine'
    | '/agents/$agentId'
    | '/crm/$contactId'
    | '/enterprise-brain/$itemId'
    | '/missions/$missionId'
    | '/agents/'
    | '/crm/'
    | '/enterprise-brain/'
    | '/missions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/help-center'
    | '/insights'
    | '/integrations-hub'
    | '/organization'
    | '/security-center'
    | '/system-settings'
    | '/workflow-engine'
    | '/agents/$agentId'
    | '/crm/$contactId'
    | '/enterprise-brain/$itemId'
    | '/missions/$missionId'
    | '/agents'
    | '/crm'
    | '/enterprise-brain'
    | '/missions'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/help-center'
    | '/insights'
    | '/integrations-hub'
    | '/organization'
    | '/security-center'
    | '/system-settings'
    | '/workflow-engine'
    | '/agents/$agentId'
    | '/crm/$contactId'
    | '/enterprise-brain/$itemId'
    | '/missions/$missionId'
    | '/agents/'
    | '/crm/'
    | '/enterprise-brain/'
    | '/missions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  HelpCenterRoute: typeof HelpCenterRoute
  InsightsRoute: typeof InsightsRoute
  IntegrationsHubRoute: typeof IntegrationsHubRoute
  OrganizationRoute: typeof OrganizationRoute
  SecurityCenterRoute: typeof SecurityCenterRoute
  SystemSettingsRoute: typeof SystemSettingsRoute
  WorkflowEngineRoute: typeof WorkflowEngineRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  CrmContactIdRoute: typeof CrmContactIdRoute
  EnterpriseBrainItemIdRoute: typeof EnterpriseBrainItemIdRoute
  MissionsMissionIdRoute: typeof MissionsMissionIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CrmIndexRoute: typeof CrmIndexRoute
  EnterpriseBrainIndexRoute: typeof EnterpriseBrainIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations-hub': {
      id: '/integrations-hub'
      path: '/integrations-hub'
      fullPath: '/integrations-hub'
      preLoaderRoute: typeof IntegrationsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-center': {
      id: '/security-center'
      path: '/security-center'
      fullPath: '/security-center'
      preLoaderRoute: typeof SecurityCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-settings': {
      id: '/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof SystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-engine': {
      id: '/workflow-engine'
      path: '/workflow-engine'
      fullPath: '/workflow-engine'
      preLoaderRoute: typeof WorkflowEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/$contactId': {
      id: '/crm/$contactId'
      path: '/crm/$contactId'
      fullPath: '/crm/$contactId'
      preLoaderRoute: typeof CrmContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-brain/': {
      id: '/enterprise-brain/'
      path: '/enterprise-brain'
      fullPath: '/enterprise-brain/'
      preLoaderRoute: typeof EnterpriseBrainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-brain/$itemId': {
      id: '/enterprise-brain/$itemId'
      path: '/enterprise-brain/$itemId'
      fullPath: '/enterprise-brain/$itemId'
      preLoaderRoute: typeof EnterpriseBrainItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId': {
      id: '/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof MissionsMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  HelpCenterRoute: HelpCenterRoute,
  InsightsRoute: InsightsRoute,
  IntegrationsHubRoute: IntegrationsHubRoute,
  OrganizationRoute: OrganizationRoute,
  SecurityCenterRoute: SecurityCenterRoute,
  SystemSettingsRoute: SystemSettingsRoute,
  WorkflowEngineRoute: WorkflowEngineRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  CrmContactIdRoute: CrmContactIdRoute,
  EnterpriseBrainItemIdRoute: EnterpriseBrainItemIdRoute,
  MissionsMissionIdRoute: MissionsMissionIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CrmIndexRoute: CrmIndexRoute,
  EnterpriseBrainIndexRoute: EnterpriseBrainIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
