// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgxaqwzikqgovvucvwsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneGFxd3ppa3Fnb3Z2dWN2d3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxNzM4ODAsImV4cCI6MjEwMTc0OTg4MH0.t1l3HreUAPgRxEuLwtXqg51SVvTH7jSbyQg7JSWYPGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});